openapi: 3.0.0
info:
  title: SERVER - Requirements Management
  version: 1.0.0
  description: Requirements tracking, linking with testcases/scripts, coverage analysis
servers:
  - url: '{{server_url}}'
paths:
  /requirements/create:
    post:
      summary: Create Requirement
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /requirements/list:
    get:
      summary: List Requirements
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /requirements/{requirement_id}:
    get:
      summary: Get Requirement by ID
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: requirement_id
        in: path
        required: true
        schema:
          type: string
    put:
      summary: Update Requirement
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /requirements/link-testcase:
    post:
      summary: Link Testcase to Requirement
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /requirements/coverage/summary:
    get:
      summary: Get Coverage Summary
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
