openapi: 3.0.0
info:
  title: SERVER - User Interface Management
  version: 1.0.0
  description: UI definition management, compatibility checking, interface CRUD
servers:
  - url: '{{server_url}}'
paths:
  /userinterface/getAllUserInterfaces:
    get:
      summary: Get All User Interfaces
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /userinterface/createUserInterface:
    post:
      summary: Create User Interface
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /userinterface/getUserInterface/{interface_id}:
    get:
      summary: Get User Interface by ID
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: interface_id
        in: path
        required: true
        schema:
          type: string
  /userinterface/updateUserInterface/{interface_id}:
    put:
      summary: Update User Interface
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: interface_id
        in: path
        required: true
        schema:
          type: string
  /userinterface/deleteUserInterface/{interface_id}:
    delete:
      summary: Delete User Interface
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: interface_id
        in: path
        required: true
        schema:
          type: string
