openapi: 3.0.0
info:
  title: SERVER - Metrics & Analytics
  version: 1.0.0
  description: Performance metrics, navigation analytics, execution history
servers:
  - url: '{{server_url}}'
paths:
  /metrics/tree/{test_navigation_id}:
    get:
      summary: Get Tree Metrics
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: test_navigation_id
        in: path
        required: true
        schema:
          type: string
  /metrics/node/node-id/{test_navigation_id}:
    get:
      summary: Get Node Metrics
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: test_navigation_id
        in: path
        required: true
        schema:
          type: string
  /metrics/edge/edge-id/{test_navigation_id}:
    get:
      summary: Get Edge Metrics
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: test_navigation_id
        in: path
        required: true
        schema:
          type: string
  /metrics/history/actions/edge-id/{test_navigation_id}:
    get:
      summary: Get Action History
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: test_navigation_id
        in: path
        required: true
        schema:
          type: string
  /metrics/history/verifications/node-id/{test_navigation_id}:
    get:
      summary: Get Verification History
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: test_navigation_id
        in: path
        required: true
        schema:
          type: string
