openapi: 3.0.0
info:
  title: SERVER - Testcase Management
  version: 1.0.0
  description: >-
    Test case CRUD operations including creation, update, listing, execution,
    and folder/tag management for organizing test cases.
servers:
  - url: '{{server_url}}'
paths:
  /testcase/list:
    get:
      summary: List All Testcases
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: include_inactive
          in: query
          description: Include inactive/deleted testcases
          schema:
            type: boolean
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
      description: Get all testcases for a team
  /testcase/save:
    post:
      summary: Create Testcase
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
      description: Create a new test case with graph structure
  /testcase/{test_testcase_id}:
    get:
      summary: Get Testcase by ID
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
      description: Retrieve a specific testcase by ID
    parameters:
      - name: test_testcase_id
        in: path
        required: true
        schema:
          type: string
    delete:
      summary: Delete Testcase
      tags: []
      parameters:
        - name: team_id
          in: query
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
      description: Delete a testcase
