export const infraredRemoteConfig = {
  remote_info: {
    name: 'Infrared Remote',
    type: 'ir_remote' as const,
  },
  panel_layout: {
    collapsed: {
      width: '180px',
      height: '240px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '320px',
      height: '480px',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: false,
    header: {
      height: '48px',
      fontSize: '0.875rem',
      fontWeight: 'bold',
      iconSize: 'small',
      padding: '8px',
      backgroundColor: '#1E1E1E',
      borderColor: '#333',
      textColor: '#ffffff',
    },
  },
  remote_layout: {
    collapsed: {
      width: '140px',
      height: '200px',
      scale: 0.7,
      padding: '20px',
    },
    expanded: {
      width: '280px',
      height: '430px',
      scale: 1.0,
      padding: '20px',
    },
    background_image: {
      url: '/ir-remote.png',
      width: 280,
      height: 430,
    },
    global_offset: {
      x: 0,
      y: 0,
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      position: { x: 70, y: 40 },
      size: { width: 30, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Power button',
    },
    source: {
      key: 'SOURCE',
      position: { x: 40, y: 70 },
      size: { width: 25, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Source/Input button',
    },
    mute: {
      key: 'MUTE',
      position: { x: 100, y: 70 },
      size: { width: 25, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Mute button',
    },
    num_1: {
      key: '1',
      position: { x: 40, y: 100 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Number 1',
    },
    num_2: {
      key: '2',
      position: { x: 70, y: 100 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Number 2',
    },
    num_3: {
      key: '3',
      position: { x: 100, y: 100 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Number 3',
    },
    num_4: {
      key: '4',
      position: { x: 40, y: 130 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Number 4',
    },
    num_5: {
      key: '5',
      position: { x: 70, y: 130 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Number 5',
    },
    num_6: {
      key: '6',
      position: { x: 100, y: 130 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Number 6',
    },
    num_7: {
      key: '7',
      position: { x: 40, y: 160 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Number 7',
    },
    num_8: {
      key: '8',
      position: { x: 70, y: 160 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Number 8',
    },
    num_9: {
      key: '9',
      position: { x: 100, y: 160 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Number 9',
    },
    num_0: {
      key: '0',
      position: { x: 70, y: 190 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Number 0',
    },
    volume_up: {
      key: 'VOLUME_UP',
      position: { x: 40, y: 220 },
      size: { width: 25, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Volume up',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      position: { x: 100, y: 220 },
      size: { width: 25, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Channel up',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      position: { x: 40, y: 250 },
      size: { width: 25, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Volume down',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      position: { x: 100, y: 250 },
      size: { width: 25, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Channel down',
    },
    up: {
      key: 'UP',
      position: { x: 70, y: 280 },
      size: { width: 25, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Navigation up',
    },
    left: {
      key: 'LEFT',
      position: { x: 45, y: 300 },
      size: { width: 15, height: 25 },
      shape: 'rectangle' as const,
      comment: 'Navigation left',
    },
    center: {
      key: 'OK',
      position: { x: 70, y: 305 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'OK/Select',
    },
    right: {
      key: 'RIGHT',
      position: { x: 95, y: 300 },
      size: { width: 15, height: 25 },
      shape: 'rectangle' as const,
      comment: 'Navigation right',
    },
    down: {
      key: 'DOWN',
      position: { x: 70, y: 330 },
      size: { width: 25, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Navigation down',
    },
    menu: {
      key: 'MENU',
      position: { x: 40, y: 360 },
      size: { width: 25, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Menu button',
    },
    back: {
      key: 'BACK',
      position: { x: 100, y: 360 },
      size: { width: 25, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Back/Exit button',
    },
  },
} as const;

export type InfraredRemoteConfig = typeof infraredRemoteConfig;
