# Agent Configuration: Result Analyzer
# Version: 2.3.0
# Author: system
#
# Analyzes script and test results to detect false positives.
#
# TWO MODES:
# 1. Chat Mode: User selects analyzer and provides report URL directly
# 2. Event Mode: Automatically triggered via queue when execution completes
#
# Architecture:
# - Chat requests → Immediate response (separate thread)
# - Event triggers → Background queue (doesn't block chat)
#
---
metadata:
  id: analyzer
  name: Result Analyzer
  nickname: Sherlock
  selectable: true  # Users can select in chat
  default: false
  version: 2.3.0
  author: system
  description: "Analyzes script and test results"
  tags:
    - analysis
    - autonomous
    - validation
  suggestions:
    - "Analyze this report: http://..."
    - "What's in the analysis queue?"

triggers:
  - type: chat.message
    priority: high  # Chat always takes priority

  - type: script.completed
    priority: normal  # Queued for background processing
  
  - type: testcase.completed
    priority: normal  # Queued for background processing

event_pools:
  - shared.executions
  - shared.results

subagents: []

# Micro-skills (2-3 tools each)
available_skills:
  - validate
  - analyze
  - validate-result
  - detect-false-positive
  - generate-report

# Router mode tools - for quick queries and fetching execution data
skills:
  - get_execution_status
  - get_last_execution_event
  - fetch_execution_report
  - fetch_execution_logs
  - get_analysis_queue_status

permissions:
  devices:
    - read

  database:
    - read
    - write.analysis_results

  external:
    - slack
    - http  # Needed for fetching reports/logs via URL

config:
  enabled: true
  max_parallel_tasks: 5
  approval_required_for: []
  auto_retry: true
  feedback_collection: false
  timeout_seconds: 300
