# Agent Configuration: Result Analyzer
# Version: 2.5.0
# Author: system
#
# Analyzes script execution results to detect false positives.
#
# TWO MODES:
# 1. Chat Mode: User provides report URL directly
# 2. Queue Mode: Background processing from p2_scripts queue
#
# Queue Flow:
# 1. Task arrives: {type: 'script', id: '<script_id>', data: {...}}
# 2. Agent fetches full script data from database (html_report_r2_url, logs, etc.)
# 3. Agent uses fetch_execution_report/fetch_execution_logs tools
# 4. Agent classifies: BUG | SCRIPT_ISSUE | SYSTEM_ISSUE | UNKNOWN
#
---
metadata:
  id: analyzer
  name: Result Analyzer
  nickname: Sherlock
  selectable: false
  default: false
  version: 2.5.0
  author: system
  description: "Analyzes script and test results"
  tags:
    - analysis
    - scripts
    - validation

triggers:

  - type: redis.queue.script
    priority: normal

subagents: []

available_skills:
  - validate
  - analyze

# Router mode tools
skills:
  - get_execution_result

permissions:
  devices:
    - read

  database:
    - read
    - write.analysis_results

  external:
    - http

config:
  enabled: true
  background_queues: ['p2_scripts']  # Only scripts, alerts handled by different agent
  max_parallel_tasks: 5
  approval_required_for: []
  auto_retry: true
  feedback_collection: false
  timeout_seconds: 300
