# Agent Configuration: Result Analyzer
# Version: 2.4.0
# Author: system
#
# Analyzes script and test results to detect false positives.
#
# TWO MODES:
# 1. Chat Mode: User selects analyzer and provides report URL directly
# 2. Event Mode: Automatically triggered via queue when execution completes
#
# Architecture:
# - Chat requests → Immediate response (separate thread)
# - Event triggers → Background queue (doesn't block chat)
#
---
metadata:
  id: analyzer
  name: Result Analyzer
  nickname: Sherlock
  selectable: true  # Users can select in chat
  default: false
  version: 2.4.0
  author: system
  description: "Analyzes script and test results"
  tags:
    - analysis
    - autonomous
    - validation
  suggestions:
    - "Analyze this report: http://..."
    - "What's in the analysis queue?"

triggers:
  - type: chat.message
    priority: high  # Chat always takes priority

  - type: script.completed
    priority: normal  # Queued for background processing
  
  - type: testcase.completed
    priority: normal  # Queued for background processing

subagents: []

# Micro-skills this agent can load (from skills/definitions/)
available_skills:
  - validate   # Result validation using report URLs
  - analyze    # Failure classification using report URLs

# Router mode MCP tools (minimal - for quick queries)
skills:
  - get_last_execution_event
  - fetch_execution_report
  - get_analysis_queue_status

permissions:
  devices:
    - read

  database:
    - read
    - write.analysis_results

  external:
    - slack
    - http  # Needed for fetching reports/logs via URL

config:
  enabled: true
  max_parallel_tasks: 5
  approval_required_for: []
  auto_retry: true
  feedback_collection: false
  timeout_seconds: 300
