# Agent Configuration: Result Analyzer
# Version: 2.1.0
# Author: system
#
# Analyzes script and test results to detect false positives.
# Not user-selectable, triggered by execution completion.
# Token-optimized micro-skills.
#
---
metadata:
  id: analyzer
  name: Result Analyzer
  nickname: Sherlock
  selectable: false
  default: false
  version: 2.1.0
  author: system
  description: "Analyzes script and test results"
  tags:
    - analysis
    - autonomous
    - validation
  suggestions: []

triggers:
  - type: chat.message
    priority: normal

  - type: script.completed
    priority: normal
  
  - type: testcase.completed
    priority: normal

event_pools:
  - shared.executions
  - shared.results

subagents: []

# Micro-skills (2-3 tools each)
available_skills:
  - validate
  - analyze
  - validate-result
  - detect-false-positive
  - generate-report

# Router mode tools (minimal)
skills:
  - get_execution_status

permissions:
  devices:
    - read

  database:
    - read
    - write.analysis_results

  external:
    - slack

config:
  enabled: true
  max_parallel_tasks: 5
  approval_required_for: []
  auto_retry: true
  feedback_collection: false
  timeout_seconds: 300
