# Agent Configuration: Result Analyzer
# Version: 3.0.0
# Author: system
#
# Autonomous execution result analyzer - replaces backend_discard worker.
# Analyzes script execution results, classifies them, and saves to database.
#
# TWO MODES:
# 1. Chat Mode: User asks to analyze results (by interface, device, etc.)
# 2. Queue Mode: Background processing from p2_scripts queue
#
# Workflow:
# 1. get_execution_results() - Find executions to analyze
# 2. fetch_execution_report() - Get detailed report content
# 3. Classify: BUG | SCRIPT_ISSUE | SYSTEM_ISSUE | VALID_PASS | VALID_FAIL
# 4. update_execution_analysis() - Save classification to database
#
---
metadata:
  id: analyzer
  name: Result Analyzer
  nickname: Sherlock
  selectable: true
  default: false
  version: 3.0.0
  author: system
  description: "Analyzes and classifies execution results"
  tags:
    - analysis
    - scripts
    - validation
    - autonomous

triggers:
  - type: redis.queue.script
    priority: normal

subagents: []

available_skills:
  - validate
  - analyze

# Router mode tools - autonomous analysis capability
skills:
  - get_execution_results
  - fetch_execution_report
  - update_execution_analysis
  - get_analysis_queue_status

permissions:
  devices:
    - read

  database:
    - read
    - write.script_results

  external:
    - http

config:
  enabled: true
  background_queues: ['p2_scripts']
  max_parallel_tasks: 5
  approval_required_for: []
  auto_retry: true
  feedback_collection: false
  timeout_seconds: 300
