# Agent Configuration: Result Analyzer
# Version: 3.0.2
# Author: system
#
# THREE OPERATING MODES:
#
# ═══════════════════════════════════════════════════════════════
# 1. QUEUE MODE (Redis trigger - background processing)
# ═══════════════════════════════════════════════════════════════
#    - Triggered by: redis.queue.script (p2_scripts queue)
#    - Input: Redis provides report_url + script_result_id directly
#    - Workflow:
#      1. fetch_execution_report(report_url) - from Redis message
#      2. Classify result
#      3. update_execution_analysis(script_result_id) - save to DB
#    - NO need to call get_execution_results() - Redis gives us the data
#
# ═══════════════════════════════════════════════════════════════
# 2. FETCH MODE (Chat - user wants to VIEW results)
# ═══════════════════════════════════════════════════════════════
#    - Triggered by: "fetch/show/get last result"
#    - Workflow:
#      1. get_execution_results() - query DB (includes existing analysis)
#      2. fetch_execution_report() - (optional) show report content
#    - DO NOT call update_execution_analysis()
#
# ═══════════════════════════════════════════════════════════════
# 3. ANALYZE MODE (Chat - user wants to ANALYZE a result)
# ═══════════════════════════════════════════════════════════════
#    - Triggered by: "analyze/classify this result"
#    - Workflow:
#      1. get_execution_results() - find execution in DB
#      2. fetch_execution_report() - get report details
#      3. Classify: BUG | SCRIPT_ISSUE | SYSTEM_ISSUE | VALID_PASS | VALID_FAIL
#      4. update_execution_analysis() - save to DB
#
---
metadata:
  id: analyzer
  name: Result Analyzer
  nickname: Sherlock
  selectable: true
  default: false
  version: 3.0.2
  author: system
  description: "Fetches and analyzes execution results"
  tags:
    - analysis
    - scripts
    - validation
    - autonomous

triggers:
  - type: redis.queue.script
    priority: normal

subagents: []

available_skills:
  - validate
  - analyze

# Router tools:
# - get_execution_results: Query DB (for chat FETCH/ANALYZE modes)
# - fetch_execution_report: Parse report URL (for all modes)
# - get_analysis_queue_status: Show Redis queue + session stats
skills:
  - fetch_execution_report
  - get_analysis_queue_status

permissions:
  devices:
    - read

  database:
    - read
    - write.script_results

  external:
    - http

config:
  enabled: true
  background_queues: ['p2_scripts']
  max_parallel_tasks: 5
  approval_required_for: []
  auto_retry: true
  feedback_collection: false
  timeout_seconds: 300
