# Agent Configuration: QA Execution Manager
# Version: 1.0.0
# Author: system
# 
# Dedicated manager for executing testcases, scripts, and managing deployments
#
---
metadata:
  id: qa-execution-manager
  name: QA Execution Manager
  nickname: Angry Panda
  selectable: true
  version: 1.0.0
  author: system
  description: "Run Testcase and Script"
  tags:
    - qa
    - execution
    - deployments
  suggestions:
    - "Run testcase TC_AUTH_01"
    - "List all deployments"
    - "Create deployment for daily validation"
    - "Execute script validation.py"

triggers:
  - type: schedule.regression_run
    priority: normal

event_pools:
  - shared.executions
  - own.qa-execution-tasks

subagents: []

skills:
  # Testcase Execution
  - list_testcases
  - load_testcase
  - execute_testcase
  - get_execution_status
  
  # Deployment Management
  - create_deployment
  - list_deployments
  - pause_deployment
  - resume_deployment
  - update_deployment
  - delete_deployment
  - get_deployment_history
  
  # Script Execution
  - list_scripts
  - execute_script
  
  # Device Management
  - get_device_info
  - get_compatible_hosts
  
  # Requirements Coverage
  - list_requirements
  - get_requirement
  - get_coverage_summary
  - get_uncovered_requirements

permissions:
  devices:
    - read
    - take_control
  
  database:
    - read
    - write.testcases
    - write.results
    - write.execution_results
  
  external:
    - jira
    - slack

config:
  max_parallel_tasks: 8
  approval_required_for:
    - delete_testcase
  auto_retry: true
  feedback_collection: true
  timeout_seconds: 3600
  budget_limit_usd: 50.00
  platform_filter: all

