# Agent Configuration: QA Mobile Manager
# Version: 1.0.0
# Author: system
# 
# Specialized QA manager for Android mobile devices
# Uses ADB for UI hierarchy (dump_ui_elements works)
#
---
metadata:
  id: qa-mobile-manager
  name: QA Mobile Manager
  nickname: Scout
  selectable: true
  version: 1.0.0
  author: system
  description: "Android mobile QA with ADB. Control: take_control once → all operations (get_device_info, navigate, actions) → release_control once. Never release mid-task."
  tags:
    - qa
    - mobile
    - android
    - adb
  suggestions:
    - "Test app on Android Pixel 5"
    - "Validate touch gestures on mobile"
    - "Check app crash handling"
    - "Test offline mode behavior"

triggers:
  - type: alert.app_crash
    priority: critical
    filters:
      platform: mobile
  
  - type: alert.anr
    priority: critical
    filters:
      platform: mobile
  
  - type: build.deployed
    priority: high
    filters:
      platform: mobile
  
  - type: schedule.mobile_regression
    priority: normal

event_pools:
  - shared.alerts
  - shared.builds
  - own.qa-mobile-tasks

subagents: []  # Scout works alone with all its skills

skills:
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  - take_control
  - release_control
  - navigate_to_node
  - get_device_info
  - get_compatible_hosts
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - capture_screenshot
  - create_node
  - update_node
  - delete_node
  - get_node
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - save_node_screenshot
  - execute_device_action
  - list_actions
  - list_verifications
  - verify_node

permissions:
  devices:
    - read
    - take_control
  
  database:
    - read
    - write.testcases
    - write.results
    - write.execution_results
  
  external:
    - jira
    - slack

config:
  max_parallel_tasks: 4
  approval_required_for:
    - create_jira_ticket
    - delete_testcase
  auto_retry: true
  feedback_collection: true
  timeout_seconds: 1800
  budget_limit_usd: 30.00
  platform_filter: mobile
