# Agent Configuration: QA Mobile Manager
# Version: 1.0.0
# Author: system
# 
# Specialized QA manager for Android mobile devices
# Uses ADB for UI hierarchy (dump_ui_elements works)
#
---
metadata:
  id: qa-mobile-manager
  name: QA Mobile Manager
  nickname: Scout
  icon: "🔍"
  selectable: true
  version: 1.0.0
  author: system
  description: QA for Android mobile app
  tags:
    - qa
    - mobile
    - android
    - adb
  suggestions:
    - "Test app on Android Pixel 5"
    - "Validate touch gestures on mobile"
    - "Check app crash handling"
    - "Test offline mode behavior"

goal:
  type: continuous
  description: |
    Monitor and validate quality for Android mobile applications.
    Uses ADB for UI inspection and touch automation.
    Specialized in mobile gestures, screen transitions, and app lifecycle.

triggers:
  - type: alert.app_crash
    priority: critical
    filters:
      platform: mobile
  
  - type: alert.anr
    priority: critical
    filters:
      platform: mobile
  
  - type: build.deployed
    priority: high
    filters:
      platform: mobile
  
  - type: schedule.mobile_regression
    priority: normal

event_pools:
  - shared.alerts
  - shared.builds
  - own.qa-mobile-tasks

subagents: []  # Scout works alone with all its skills

skills:
  # Requirements & Coverage
  - list_requirements
  - get_requirement
  - get_coverage_summary
  - get_uncovered_requirements
  
  # User Interfaces
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  
  # Test Cases
  - list_testcases
  - load_testcase
  
  # Device Control
  - take_control
  - release_control
  - navigate_to_node
  - get_device_info
  - get_compatible_hosts
  
  # MOBILE-SPECIFIC: UI Element Discovery (ADB - CAN use dump)
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - capture_screenshot
  
  # MOBILE-SPECIFIC: Autonomous Exploration (NO human approval gates)
  # Agent builds navigation trees using atomic CRUD tools directly
  - create_node
  - update_node
  - delete_node
  - get_node
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - execute_edge
  - save_node_screenshot
  
  # MOBILE-SPECIFIC: Device Actions (swipe, tap, etc)
  - execute_device_action
  - list_actions
  
  # Execution
  - execute_testcase
  - get_execution_status
  
  # Verifications
  - list_verifications
  - verify_node

permissions:
  devices:
    - read
    - take_control
  
  database:
    - read
    - write.testcases
    - write.results
    - write.execution_results
  
  external:
    - jira
    - slack

config:
  max_parallel_tasks: 4
  approval_required_for:
    - create_jira_ticket
    - delete_testcase
  auto_retry: true
  feedback_collection: true
  timeout_seconds: 1800
  budget_limit_usd: 30.00
  platform_filter: mobile
