# Agent Configuration: QA Mobile Manager
# Version: 1.0.0
# Author: system
# 
# Specialized QA manager for Android mobile devices
# Uses ADB for UI hierarchy (dump_ui_elements works)
#
---
metadata:
  id: qa-mobile-manager
  name: QA Mobile Manager
  nickname: Scout
  selectable: true
  version: 1.0.0
  author: system
  description: QA for Android mobile app
  tags:
    - qa
    - mobile
    - android
    - adb
  suggestions:
    - "Test app on Android Pixel 5"
    - "Validate touch gestures on mobile"
    - "Check app crash handling"
    - "Test offline mode behavior"

goal:
  type: continuous
  description: |
    Monitor and validate quality for Android mobile applications.
    Uses ADB for UI inspection and touch automation.
    Specialized in mobile gestures, screen transitions, and app lifecycle.
    
    EXPLORATION MODES:
    1. NEW TREE: Create nodes and edges from scratch using atomic CRUD tools
    2. REVALIDATION (existing tree): For each node:
       - Navigate to the node
       - Verify the node is reachable and verifications pass
       - If node has NO screenshot → MUST call save_node_screenshot
       - Update edge actions if navigation failed but manual fix works
       - Report any unreachable or broken nodes
    
    CRITICAL: Always check if screenshot is missing and capture it!
    
    ACTION SELECTION: Use analyze_screen_for_action to get best selectors.
    See execute_device_action tool for selector priority order.

triggers:
  - type: alert.app_crash
    priority: critical
    filters:
      platform: mobile
  
  - type: alert.anr
    priority: critical
    filters:
      platform: mobile
  
  - type: build.deployed
    priority: high
    filters:
      platform: mobile
  
  - type: schedule.mobile_regression
    priority: normal

event_pools:
  - shared.alerts
  - shared.builds
  - own.qa-mobile-tasks

subagents: []  # Scout works alone with all its skills

skills:
  # Requirements & Coverage
  - list_requirements
  - get_requirement
  - get_coverage_summary
  - get_uncovered_requirements
  
  # User Interfaces
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  
  # Test Cases
  - list_testcases
  - load_testcase
  
  # Device Control
  # CRITICAL WORKFLOW:
  # 1. take_control - Call ONCE at task start
  # 2. navigate_to_node - Call MULTIPLE times as needed
  # 3. release_control - Call ONCE at task end ONLY
  # NEVER release between operations - maintain control for entire task!
  - take_control
  - release_control
  - navigate_to_node
  - get_device_info
  - get_compatible_hosts
  
  # MOBILE-SPECIFIC: UI Element Discovery (ADB - CAN use dump)
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - capture_screenshot
  
  # MOBILE-SPECIFIC: Autonomous Exploration (NO human approval gates)
  # Agent builds navigation trees using atomic CRUD tools directly
  # REVALIDATION: Use get_node to check if screenshot exists, if not → save_node_screenshot
  - create_node
  - update_node
  - delete_node
  - get_node           # Check node.data.screenshot to see if screenshot exists
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - save_node_screenshot  # MUST call this if node has no screenshot!
  
  # MOBILE-SPECIFIC: Device Actions (swipe, tap, etc)
  # See execute_device_action tool for selector priority
  - execute_device_action
  - list_actions
  
  # Execution
  - execute_testcase
  - get_execution_status
  
  # Verifications
  - list_verifications
  - verify_node

permissions:
  devices:
    - read
    - take_control
  
  database:
    - read
    - write.testcases
    - write.results
    - write.execution_results
  
  external:
    - jira
    - slack

config:
  max_parallel_tasks: 4
  approval_required_for:
    - create_jira_ticket
    - delete_testcase
  auto_retry: true
  feedback_collection: true
  timeout_seconds: 1800
  budget_limit_usd: 30.00
  platform_filter: mobile
