# Agent Configuration: QA STB Manager
# Version: 1.0.0
# Author: system
# 
# Specialized QA manager for set-top box and TV platforms
# Uses screenshot + AI vision (NOT dump_ui_elements - STB cannot dump UI hierarchy)
#
---
metadata:
  id: qa-stb-manager
  name: QA STB Manager
  nickname: Watcher
  icon: "📺"
  selectable: true
  version: 1.0.0
  author: system
  description: QA for STB and TV platforms
  tags:
    - qa
    - stb
    - tv
    - remote

goal:
  type: continuous
  description: |
    Monitor and validate quality for STB and TV platforms.
    Uses AI vision for screen analysis (no UI hierarchy access).
    Specialized in EPG, remote control, D-pad navigation.

triggers:
  - type: alert.blackscreen
    priority: critical
    filters:
      platform: stb
  
  - type: alert.no_signal
    priority: critical
    filters:
      platform: stb
  
  - type: alert.epg_timeout
    priority: high
    filters:
      platform: stb
  
  - type: build.deployed
    priority: high
    filters:
      platform: stb
  
  - type: schedule.stb_regression
    priority: normal

event_pools:
  - shared.alerts
  - shared.builds
  - own.qa-stb-tasks

subagents:
  - id: explorer
    version: ">=1.0.0"
    delegate_for:
      - stb_exploration
      - dpad_navigation_mapping
  
  - id: executor
    version: ">=1.0.0"
    delegate_for:
      - stb_test_execution
      - remote_control_automation

skills:
  # Requirements & Coverage
  - list_requirements
  - get_requirement
  - get_coverage_summary
  - get_uncovered_requirements
  
  # User Interfaces
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  
  # Test Cases
  - list_testcases
  - load_testcase
  
  # Device Control
  - take_control
  - navigate_to_node
  - get_device_info
  - get_compatible_hosts
  
  # STB-SPECIFIC: Screenshot + AI Vision (NO dump_ui_elements!)
  - capture_screenshot
  - get_transcript
  
  # STB-SPECIFIC: Remote Control & D-pad
  - execute_device_action
  - list_actions
  
  # STB-SPECIFIC: AI Exploration
  - start_ai_exploration
  - approve_exploration_plan
  - validate_exploration_edges
  - get_node_verification_suggestions
  - approve_node_verifications
  - finalize_exploration
  
  # STB-SPECIFIC: Tree Building
  - create_node
  - create_edge
  - update_node
  - update_edge
  - save_node_screenshot
  
  # Execution
  - execute_testcase
  - get_execution_status
  
  # Verifications
  - list_verifications
  - verify_node

permissions:
  devices:
    - read
    - take_control
  
  database:
    - read
    - write.testcases
    - write.results
    - write.execution_results
  
  external:
    - jira
    - slack

config:
  max_parallel_tasks: 3
  approval_required_for:
    - create_jira_ticket
    - delete_testcase
  auto_retry: true
  feedback_collection: true
  timeout_seconds: 2400
  budget_limit_usd: 30.00
  platform_filter: stb
