# Agent Configuration: QA Web Manager
# Version: 1.0.0
# Author: system
# 
# Specialized QA manager for web-based userinterfaces
# Focuses on web applications, browser-based testing, and web-specific validations
#
---
metadata:
  id: qa-web-manager
  name: QA Web Manager
  nickname: Sherlock
  selectable: true
  version: 1.0.0
  author: system
  description: "Web QA with browser automation. Control: take_control once → all operations → release_control once. Never release mid-task."
  tags:
    - qa
    - web
    - browser
    - automation
  suggestions:
    - "Automate login flow for sauce-demo"
    - "Test responsive design on Chrome"
    - "Validate form submissions"
    - "Check page load performance"

triggers:
  - type: alert.blackscreen
    priority: critical
    filters:
      platform: web
  
  - type: alert.page_load_timeout
    priority: high
    filters:
      platform: web
  
  - type: build.deployed
    priority: high
    filters:
      platform: web
  
  - type: schedule.web_regression
    priority: normal

event_pools:
  - shared.alerts
  - shared.builds
  - own.qa-web-tasks

subagents: []  # Sherlock works alone with all its skills

skills:
  - list_requirements
  - get_requirement
  - get_coverage_summary
  - get_uncovered_requirements
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  - list_testcases
  - load_testcase
  - take_control
  - release_control
  - navigate_to_node
  - get_device_info
  - get_compatible_hosts
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - capture_screenshot
  - create_node
  - update_node
  - delete_node
  - get_node
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - save_node_screenshot
  - execute_testcase
  - get_execution_status
  - execute_device_action
  - list_verifications
  - verify_node

permissions:
  devices:
    - read
    - take_control
  
  database:
    - read
    - write.testcases
    - write.results
    - write.execution_results
  
  external:
    - jira
    - slack

config:
  max_parallel_tasks: 5
  approval_required_for:
    - create_jira_ticket
    - delete_testcase
  auto_retry: true
  feedback_collection: true
  timeout_seconds: 1800
  budget_limit_usd: 30.00
  platform_filter: web
