#!/bin/bash

# VirtualPyTest - Install backend_host
# This script installs backend_host dependencies

set -e

echo "🔧 Installing VirtualPyTest backend_host..."

# Get to project root directory (from setup/local to project root)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Change to project root
cd "$PROJECT_ROOT"

# Check if we're in the right directory
if [ ! -f "README.md" ] || [ ! -d "backend_host" ]; then
    echo "❌ Could not find virtualpytest project root directory"
    echo "Current directory: $(pwd)"
    exit 1
fi

# Create virtual environment if it doesn't exist
if [ ! -d "venv" ]; then
    echo "🐍 Creating Python virtual environment..."
    python3 -m venv venv
    echo "✅ Virtual environment created"
fi

# Activate virtual environment
echo "🔌 Activating virtual environment..."
source venv/bin/activate

# Skip shared library installation - using direct imports instead
echo "📚 Shared library will be used via direct imports..."

# Skip backend_host installation - using direct imports instead
echo "⚙️ Backend_core will be used via direct imports..."

# Install system dependencies for IR remote control and desktop environment
echo "🔧 Installing IR remote control tools and XFCE4 desktop environment..."
sudo apt-get update
sudo apt-get install -y lirc v4l-utils xfce4 xfce4-goodies
echo "✅ IR tools installed - ir-ctl and lircd commands available"
echo "💡 Commands: ir-ctl --send <file>, ir-ctl --read, and lircd"
echo "✅ XFCE4 desktop environment installed"

# Configure LIRC for IR remote control
echo "🔧 Configuring LIRC for IR remote control..."
LIRC_CONFIG="/etc/lirc/lirc_options.conf"

# Check if LIRC config exists and backup if needed
if [ -f "$LIRC_CONFIG" ]; then
    echo "📝 Backing up existing LIRC configuration..."
    sudo cp "$LIRC_CONFIG" "$LIRC_CONFIG.backup.$(date +%Y%m%d_%H%M%S)"
fi

# Configure LIRC for IR hardware (keeping auto for device flexibility)
echo "📝 Configuring LIRC options..."
sudo tee "$LIRC_CONFIG" > /dev/null << 'EOF'
# LIRC configuration for VirtualPyTest IR remote control
# Auto-generated by install_host.sh

[lircd]
nodaemon        = False
driver          = default
device          = auto
output          = /var/run/lirc/lircd
pidfile         = /var/run/lirc/lircd.pid
plugindir       = /usr/lib/aarch64-linux-gnu/lirc/plugins
permission      = 666
allow-simulate  = No
repeat-max      = 600

[lircmd]
uinput          = False
nodaemon        = False
EOF

# Enable and start LIRC service
echo "🚀 Starting LIRC service..."
sudo systemctl enable lircd
sudo systemctl restart lircd

# Check LIRC service status
if sudo systemctl is-active --quiet lircd; then
    echo "✅ LIRC service is running"
    
    # List available IR devices
    echo "📡 Available IR devices:"
    sudo ir-ctl --list-devices 2>/dev/null || echo "   No IR devices detected (this is normal if no IR hardware is connected)"
else
    echo "⚠️ LIRC service failed to start - check logs with: sudo journalctl -u lircd"
fi

# Install backend_host dependencies
echo "📦 Installing backend_host dependencies..."
cd backend_host
pip install -r requirements.txt

# Install Playwright browsers
echo "🌐 Installing Playwright browsers..."
playwright install chromium firefox webkit
playwright install-deps
echo "✅ Playwright browsers installed"

# Create .env file in src/ directory if it doesn't exist
cd src
if [ ! -f ".env" ]; then
    if [ -f ".env.example" ]; then
        echo "📝 Creating .env file from .env.example..."
        cp .env.example .env
        echo "✅ Created .env file - please configure it with your settings"
    else
        echo "⚠️ No .env.example found - please create .env manually"
    fi
else
    echo "✅ .env file already exists"
fi

cd ../..

# Make RAM setup script executable
chmod +x "$PROJECT_ROOT/setup/local/setup_ram_hot_storage.sh"
chmod +x "$PROJECT_ROOT/backend_host/scripts/hot_cold_archiver.py"

echo "✅ Scripts made executable"

# Setup storage directories (both RAM hot storage and SD cold storage)
echo ""
echo "📁 Setting up storage directories..."
echo "   Running setup_ram_hot_storage.sh to configure hot/cold storage..."
echo ""

# Run the RAM hot storage setup script (it handles both hot RAM and cold SD setup)
"$PROJECT_ROOT/setup/local/setup_ram_hot_storage.sh"

# Check if setup was successful
if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Storage setup completed by setup_ram_hot_storage.sh"
else
    echo ""
    echo "❌ Storage setup failed - please check errors above"
    exit 1
fi

echo ""

# Configure firewall ports for backend_host
echo "🔥 Configuring firewall for backend_host..."

# Source port checking functions
source "$PROJECT_ROOT/setup/local/check_and_open_port.sh"

# Get HOST_PORT from backend_host .env file (default 6109)
HOST_ENV_FILE="$PROJECT_ROOT/backend_host/src/.env"
HOST_PORT=$(get_port_from_env "$HOST_ENV_FILE" "HOST_PORT" "6109")

echo "🔧 Configuring firewall for backend_host ports:"
echo "   - Backend Host API: $HOST_PORT"

# Configure UFW for backend_host ports
check_and_open_port "$HOST_PORT" "backend_host API" "tcp"

# Configure XFCE4 startup
echo "🖥️ Configuring XFCE4 startup..."
XINITRC_FILE="$HOME/.xinitrc"

# Backup existing .xinitrc if it exists
if [ -f "$XINITRC_FILE" ]; then
    echo "📝 Backing up existing .xinitrc..."
    cp "$XINITRC_FILE" "$XINITRC_FILE.backup.$(date +%Y%m%d_%H%M%S)"
fi

# Create .xinitrc with XFCE4 startup configuration
cat > "$XINITRC_FILE" << 'EOF'
#!/bin/sh
# XFCE4 startup configuration for VirtualPyTest
# Auto-generated by install_host.sh

# Load X resources
xrdb "$HOME/.Xresources"

# Disable XKB xmodmap
export XKL_XMODMAP_DISABLE=1

# Start XFCE4 desktop environment
exec startxfce4
EOF

chmod +x "$XINITRC_FILE"
echo "✅ XFCE4 startup configured in $XINITRC_FILE"

# Create startup script
STARTUP_SCRIPT="$PROJECT_ROOT/setup/local/start_xfce.sh"
cat > "$STARTUP_SCRIPT" << 'EOF'
#!/bin/bash
# Start XFCE4 desktop environment for VirtualPyTest
# Auto-generated by install_host.sh

echo "🖥️ Starting XFCE4 desktop environment..."
startx
EOF

chmod +x "$STARTUP_SCRIPT"
echo "✅ Created startup script: $STARTUP_SCRIPT"

echo "✅ backend_host installation completed!"
echo ""
echo "📝 Next steps:"
echo "   1. Run: ./setup/local/install_host_services.sh  # Setup services & RAM storage"
echo "   2. Run: ./setup/local/launch_host.sh            # Start backend_host"
echo "   3. Run: ./setup/local/start_xfce.sh             # Start XFCE4 desktop (if needed)" 