services:
  # Development version with volume mounts for hot reload
  backend_host:
    build:
      context: ../
      dockerfile: backend_host/Dockerfile
    ports:
      - "6109:6109"
    volumes:
      - ../shared:/app/shared
      - ../backend_core:/app/backend_core
      - ../backend_host:/app/backend_host
      - /dev:/dev  # Hardware access
    environment:
      - HOST_PORT=6109
      - HOST_NAME=dev-host-1
      - HOST_URL=http://localhost:6109
      - SERVER_URL=http://backend_server:5109
      - DEBUG=true
      - FLASK_ENV=development
    privileged: true
    restart: unless-stopped
    command: ["python", "src/app.py"]

  backend_server:
    build:
      context: ../
      dockerfile: backend_server/Dockerfile
    ports:
      - "5109:5109"
    volumes:
      - ../shared:/app/shared
      - ../backend_server:/app/backend_server
    environment:
      - SERVER_PORT=5109
      - SERVER_URL=http://localhost:5109
      - DEBUG=true
      - FLASK_ENV=development
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
    restart: unless-stopped
    command: ["python", "src/app.py"]

  # Development frontend with Vite dev server
  frontend-dev:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5109
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend_server
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

networks:
  default:
    name: virtualpytest-dev-network 