version: '3.8'

services:
  # Backend server service (API + Grafana) - Production overrides
  backend_server:
    environment:
      # Production server configuration
      - SERVER_URL=https://virtualpytest.onrender.com
      - DEBUG=false
      - RENDER=true
      - CORS_ORIGINS=https://virtualpytest.vercel.app
      
      # Production Grafana configuration
      - GRAFANA_DOMAIN=virtualpytest.onrender.com
      - GF_SERVER_DOMAIN=virtualpytest.onrender.com
      - GF_SERVER_ROOT_URL=https://virtualpytest.onrender.com/grafana/
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      
      # Keep other settings from base compose file
      - GF_SERVER_HTTP_PORT=3001