services:
  # Production backend-host with resource limits
  backend-host:
    build:
      context: ../
      dockerfile: backend-host/Dockerfile
    ports:
      - "6109:6109"
    environment:
      - HOST_PORT=6109
      - HOST_NAME=${HOST_NAME:-prod-host-1}
      - HOST_URL=${HOST_URL:-http://localhost:6109}
      - SERVER_URL=${SERVER_URL:-http://backend-server:5109}
      - DEBUG=false
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    privileged: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Production backend-server with scaling
  backend-server:
    build:
      context: ../
      dockerfile: backend-server/Dockerfile
    ports:
      - "5109:5109"
    environment:
      - SERVER_PORT=5109
      - SERVER_URL=${SERVER_URL:-http://localhost:5109}
      - DEBUG=false
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Production frontend with Nginx
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - BACKEND_API_URL=${BACKEND_API_URL:-http://backend-server:5109}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    depends_on:
      - backend-server
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  # Nginx load balancer (optional)
  nginx-lb:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend-server
    restart: always
    profiles:
      - loadbalancer

networks:
  default:
    name: virtualpytest-prod-network 