# Production Grafana datasource configuration for VirtualPyTest
apiVersion: 1

datasources:
  # Supabase PostgreSQL - READ ONLY for fetching application data
  - name: VirtualPyTest Supabase (Read-Only)
    type: postgres
    access: proxy
    url: ${SUPABASE_DB_URI}
    jsonData:
      sslmode: require
      postgresVersion: 1300  # PostgreSQL 13+
      timescaledb: false
      maxOpenConns: 3  # Reduced connections for read-only
      maxIdleConns: 1
      connMaxLifetime: 14400  # 4 hours
    # NOT default datasource - metrics DB will be default
    isDefault: false
    # Read-only access - prevent table creation
    editable: false
    
  # Local PostgreSQL - DEFAULT for storing metrics and Grafana data (PRODUCTION)
  - name: VirtualPyTest Metrics (Local)
    type: postgres
    access: proxy
    url: postgres://grafana_prod_user:${GRAFANA_METRICS_DB_PASSWORD:-grafana_prod_secure_pass}@grafana_metrics_db:5432/grafana_metrics_prod
    jsonData:
      sslmode: disable  # Local connection, no SSL needed
      postgresVersion: 1300
      timescaledb: false
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    # Set as default datasource for metrics storage
    isDefault: true
    # Allow editing for metrics and dashboard creation
    editable: true
