# Grafana datasource configuration for VirtualPyTest Supabase PostgreSQL
apiVersion: 1

datasources:
  - name: VirtualPyTest PostgreSQL
    type: postgres
    access: proxy
    # Use single Supabase URI
    url: ${SUPABASE_DB_URI}
    jsonData:
      sslmode: require
      postgresVersion: 1300  # PostgreSQL 13+
      timescaledb: false
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400  # 4 hours
    # Set as default datasource
    isDefault: true
    # Allow editing for dashboard creation
    editable: true