"""
Action tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in action_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 2 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for action.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/action_tools.py docstrings
    """
    return [
    {
        "name": "execute_device_action",
        "description": "Execute batch of actions on a device. Supports remote commands, ADB, web actions, desktop automation. Call list_actions() first to get valid commands. MCP-formatted response with execution results\n\nExample: execute_device_action(host_name='sunri-pi1', device_id='device1', actions=[{'command': 'KEY_HOME'}])",
        "inputSchema": {
            "type": "object",
            "properties": {
                "host_name": {
                    "type": "string",
                    "description": "host name where device is connected"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                },
                "actions": {
                    "type": "array",
                    "description": "list of action dicts with command and params"
                }
            },
            "required": [
                "host_name",
                "device_id",
                "actions"
            ]
        }
    },
    {
        "name": "list_actions",
        "description": "List available actions for a device. MCP-formatted response with categorized list of available actions\n\nExample: list_actions(host_name='sunri-pi1', device_id='device1')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "host_name": {
                    "type": "string",
                    "description": "host name where device is connected"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                }
            },
            "required": [
                "host_name",
                "device_id"
            ]
        }
    }
]
