"""
Analysis tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in analysis_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 3 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for analysis.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/analysis_tools.py docstrings
    """
    return [
    {
        "name": "get_analysis_queue_status",
        "description": "Get analysis queue status with pending items and session processing stats. Queue lengths and session statistics\n\nExample: get_analysis_queue_status()",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    },
    {
        "name": "get_execution_results",
        "description": "Get execution results from database with filters. Automatically fetches and includes report content. List of execution results with pre-fetched report content\n\nExample: get_execution_results(userinterface_name='google_tv', limit=5)",
        "inputSchema": {
            "type": "object",
            "properties": {
                "userinterface_name": {
                    "type": "string",
                    "description": "filter by interface"
                },
                "device_name": {
                    "type": "string",
                    "description": "filter by device"
                },
                "host_name": {
                    "type": "string",
                    "description": "filter by host"
                },
                "success": {
                    "type": "boolean",
                    "description": "filter by success status"
                },
                "limit": {
                    "type": "integer",
                    "description": "max results default 1"
                }
            },
            "required": []
        }
    },
    {
        "name": "update_execution_analysis",
        "description": "Save analysis results to database. Success/failure status\n\nExample: update_execution_analysis(script_result_id='123', classification='BUG', explanation='Button not found')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "script_result_id": {
                    "type": "string",
                    "description": "ID of script result to update"
                },
                "discard": {
                    "type": "boolean",
                    "description": "true if false positive"
                },
                "classification": {
                    "type": "string",
                    "description": "BUG SCRIPT_ISSUE SYSTEM_ISSUE VALID_PASS VALID_FAIL"
                },
                "explanation": {
                    "type": "string",
                    "description": "brief analysis explanation"
                }
            },
            "required": [
                "script_result_id",
                "classification",
                "explanation"
            ]
        }
    }
]
