"""
Control tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in control_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 2 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for control.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/control_tools.py docstrings
    """
    return [
    {
        "name": "release_control",
        "description": "Release device control when done. Unlocks the device so others can use it. MCP-formatted response\n\nExample: release_control(host_name='sunri-pi1', device_id='device1')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "host_name": {
                    "type": "string",
                    "description": "host where device is connected"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                }
            },
            "required": [
                "host_name",
                "device_id"
            ]
        }
    },
    {
        "name": "take_control",
        "description": "Take exclusive control of a device. Locks device for exclusive use. Required before any device operations. MCP-formatted response with session_id\n\nExample: take_control(host_name='sunri-pi1', device_id='device1')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "host_name": {
                    "type": "string",
                    "description": "host where device is connected"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                }
            },
            "required": [
                "host_name",
                "device_id"
            ]
        }
    }
]
