"""
Deployment tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in deployment_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 7 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for deployment.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/deployment_tools.py docstrings
    """
    return [
    {
        "name": "create_deployment",
        "description": "Create a scheduled deployment for automated test execution. Created deployment details\n\nExample: create_deployment(name='nightly_test', host_name='sunri-pi1', device_id='device1', script_name='test.py', cron_expression='0 2 * * *')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "deployment name"
                },
                "host_name": {
                    "type": "string",
                    "description": "host where device is connected"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                },
                "script_name": {
                    "type": "string",
                    "description": "script to execute"
                },
                "cron_expression": {
                    "type": "string",
                    "description": "cron schedule"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "interface name"
                },
                "parameters": {
                    "type": "string",
                    "description": "script parameters"
                },
                "start_date": {
                    "type": "string",
                    "description": "start date"
                },
                "end_date": {
                    "type": "string",
                    "description": "end date"
                },
                "max_executions": {
                    "type": "integer",
                    "description": "max execution count"
                }
            },
            "required": [
                "name",
                "host_name",
                "device_id",
                "script_name",
                "cron_expression"
            ]
        }
    },
    {
        "name": "delete_deployment",
        "description": "Delete a deployment. Success confirmation\n\nExample: delete_deployment(deployment_id='abc123')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "deployment_id": {
                    "type": "string",
                    "description": "deployment ID to delete"
                }
            },
            "required": [
                "deployment_id"
            ]
        }
    },
    {
        "name": "get_deployment_history",
        "description": "Get execution history for a deployment. Execution history with results\n\nExample: get_deployment_history(deployment_id='abc123', limit=10)",
        "inputSchema": {
            "type": "object",
            "properties": {
                "deployment_id": {
                    "type": "string",
                    "description": "deployment ID"
                },
                "limit": {
                    "type": "integer",
                    "description": "max results default 50"
                }
            },
            "required": [
                "deployment_id"
            ]
        }
    },
    {
        "name": "list_deployments",
        "description": "List all scheduled deployments. List of deployments with status and schedules\n\nExample: list_deployments()",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    },
    {
        "name": "pause_deployment",
        "description": "Pause a running deployment. Success confirmation\n\nExample: pause_deployment(deployment_id='abc123')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "deployment_id": {
                    "type": "string",
                    "description": "deployment ID to pause"
                }
            },
            "required": [
                "deployment_id"
            ]
        }
    },
    {
        "name": "resume_deployment",
        "description": "Resume a paused deployment. Success confirmation\n\nExample: resume_deployment(deployment_id='abc123')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "deployment_id": {
                    "type": "string",
                    "description": "deployment ID to resume"
                }
            },
            "required": [
                "deployment_id"
            ]
        }
    },
    {
        "name": "update_deployment",
        "description": "Update a deployment's configuration. Updated deployment details\n\nExample: update_deployment(deployment_id='abc123', cron_expression='0 3 * * *')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "deployment_id": {
                    "type": "string",
                    "description": "deployment ID to update"
                },
                "name": {
                    "type": "string",
                    "description": "new deployment name"
                },
                "cron_expression": {
                    "type": "string",
                    "description": "new cron schedule"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "new interface name"
                },
                "parameters": {
                    "type": "string",
                    "description": "new script parameters"
                }
            },
            "required": [
                "deployment_id"
            ]
        }
    }
]
