"""
Device tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in device_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 4 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for device.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/device_tools.py docstrings
    """
    return [
    {
        "name": "get_compatible_hosts",
        "description": "Get hosts and devices compatible with a userinterface \u26a0\ufe0f CRITICAL: Use this tool BEFORE execute_device_action, navigate_to_node, execute_testcase, or generate_test_graph to find compatible hosts/devices. This tool automatically filters hosts based on the userinterface's device models and returns the first compatible host/device for immediate use. MCP-formatted response with: - compatible_hosts: List of hosts with compatible devices - recommended: Auto-selected first host and device - models: Device models required by the interface get_compatible_hosts(userinterface_name='sauce-demo') # Returns: recommended_host='your-mac', recommended_device='device1'",
        "inputSchema": {
            "type": "object",
            "properties": {
                "userinterface_name": {
                    "type": "string",
                    "description": "Interface name (e.g., 'sauce-demo'"
                }
            },
            "required": [
                "userinterface_name"
            ]
        }
    },
    {
        "name": "get_device_info",
        "description": "Get device information and capabilities Returns device list with capabilities, controllers, and status. MCP-formatted response with device information",
        "inputSchema": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "description": "Specific device, or omit for all devices"
                },
                "host_name": {
                    "type": "string",
                    "description": "Filter by host"
                }
            },
            "required": []
        }
    },
    {
        "name": "get_execution_status",
        "description": "Poll execution status for async operations Check status of actions, testcases, or other async operations. MCP-formatted response with execution status and results",
        "inputSchema": {
            "type": "object",
            "properties": {
                "execution_id": {
                    "type": "string",
                    "description": "Execution ID from async operation"
                },
                "operation_type": {
                    "type": "string",
                    "description": "'action', 'testcase', 'ai' for specific endpoints"
                }
            },
            "required": [
                "execution_id"
            ]
        }
    },
    {
        "name": "list_hosts",
        "description": "List all registered hosts Returns list of all hosts with their device counts and status. Use this to discover available hosts before calling other tools. MCP-formatted response with host list",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    }
]
