"""
Exploration tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in exploration_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 1 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for exploration.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/exploration_tools.py docstrings
    """
    return [
    {
        "name": "auto_discover_screen",
        "description": "Auto-discover screen elements, create nodes/edges, and validate them. MCP-formatted response with discovered nodes, edges, and validation results\n\nExample: auto_discover_screen(tree_id='abc', host_name='sunri-pi1', userinterface_name='google_tv')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "host_name": {
                    "type": "string",
                    "description": "host name where device is connected"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "UI interface name"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                },
                "parent_node_id": {
                    "type": "string",
                    "description": "parent node for discovered elements"
                }
            },
            "required": [
                "tree_id",
                "host_name",
                "userinterface_name"
            ]
        }
    }
]
