"""
Requirements tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in requirements_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 10 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for requirements.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/requirements_tools.py docstrings
    """
    return [
    {
        "name": "create_requirement",
        "description": "Create a new requirement MCP-formatted response with requirement_id",
        "inputSchema": {
            "type": "object",
            "properties": {
                "requirement_code": {
                    "type": "string",
                    "description": "e.g., 'REQ_PLAYBACK_001'"
                },
                "requirement_name": {
                    "type": "string",
                    "description": "e.g., 'User can play video'"
                },
                "priority": {
                    "type": "string",
                    "description": "P1, P2, P3 (default: P2"
                },
                "category": {
                    "type": "string",
                    "description": "e.g., 'playback', 'navigation'"
                }
            },
            "required": [
                "requirement_code",
                "requirement_name"
            ]
        }
    },
    {
        "name": "get_coverage_summary",
        "description": "Get coverage summary across all requirements with breakdowns by priority and category. Coverage metrics and percentages\n\nExample: get_coverage_summary()",
        "inputSchema": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "description": "filter by category"
                },
                "priority": {
                    "type": "string",
                    "description": "filter by priority"
                }
            },
            "required": []
        }
    },
    {
        "name": "get_requirement",
        "description": "Get requirement by ID. Requirement details with linked test cases\n\nExample: get_requirement(requirement_id='REQ-001')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "requirement_id": {
                    "type": "string",
                    "description": "requirement ID to fetch"
                }
            },
            "required": [
                "requirement_id"
            ]
        }
    },
    {
        "name": "get_requirement_coverage",
        "description": "Get detailed coverage for a requirement showing linked test cases and executions. Coverage details with test cases and execution stats\n\nExample: get_requirement_coverage(requirement_id='REQ-001')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "requirement_id": {
                    "type": "string",
                    "description": "requirement ID to check coverage"
                }
            },
            "required": [
                "requirement_id"
            ]
        }
    },
    {
        "name": "get_testcase_requirements",
        "description": "Get all requirements linked to a testcase. List of requirements linked to the test case\n\nExample: get_testcase_requirements(testcase_id='tc123')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "testcase_id": {
                    "type": "string",
                    "description": "test case ID"
                }
            },
            "required": [
                "testcase_id"
            ]
        }
    },
    {
        "name": "get_uncovered_requirements",
        "description": "Get all requirements without test coverage. List of uncovered requirements\n\nExample: get_uncovered_requirements()",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    },
    {
        "name": "link_testcase_to_requirement",
        "description": "Link testcase to requirement for coverage tracking MCP-formatted response",
        "inputSchema": {
            "type": "object",
            "properties": {
                "coverage_type": {
                    "type": "string",
                    "description": "'full', 'partial' (default: 'full'"
                }
            },
            "required": []
        }
    },
    {
        "name": "list_requirements",
        "description": "List all requirements. List of requirements with codes and names\n\nExample: list_requirements()",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    },
    {
        "name": "unlink_testcase_from_requirement",
        "description": "Unlink testcase from requirement. Success confirmation\n\nExample: unlink_testcase_from_requirement(testcase_id='tc1', requirement_id='req1')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "testcase_id": {
                    "type": "string",
                    "description": "test case ID"
                },
                "requirement_id": {
                    "type": "string",
                    "description": "requirement ID"
                }
            },
            "required": [
                "testcase_id",
                "requirement_id"
            ]
        }
    },
    {
        "name": "update_requirement",
        "description": "Update an existing requirement. Updated requirement details\n\nExample: update_requirement(requirement_id='123', priority='high', status='in_progress')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "requirement_id": {
                    "type": "string",
                    "description": "requirement ID to update"
                },
                "requirement_name": {
                    "type": "string",
                    "description": "new name"
                },
                "requirement_code": {
                    "type": "string",
                    "description": "new code"
                },
                "description": {
                    "type": "string",
                    "description": "new description"
                },
                "priority": {
                    "type": "string",
                    "description": "new priority"
                },
                "status": {
                    "type": "string",
                    "description": "new status"
                }
            },
            "required": [
                "requirement_id"
            ]
        }
    }
]
