"""
Screenshot tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in screenshot_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 1 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for screenshot.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/screenshot_tools.py docstrings
    """
    return [
    {
        "name": "capture_screenshot",
        "description": "Capture screenshot from device using AV controller. MCP-formatted response with screenshot URL\n\nExample: capture_screenshot(device_id='device1', host_name='sunri-pi1')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                },
                "host_name": {
                    "type": "string",
                    "description": "host name where device is connected"
                },
                "include_ui_dump": {
                    "type": "boolean",
                    "description": "include UI hierarchy dump"
                }
            },
            "required": [
                "device_id"
            ]
        }
    }
]
