"""
Screen_Analysis tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in screen_analysis_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 2 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for screen_analysis.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/screen_analysis_tools.py docstrings
    """
    return [
    {
        "name": "analyze_screen_for_action",
        "description": "Analyze screen elements to find best selector for clicking/interacting. Returns ready-to-use action parameters. MCP-formatted response with selector and action params\n\nExample: analyze_screen_for_action(elements=[...], intent='search button', platform='web')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "elements": {
                    "type": "array",
                    "description": "elements from dump_ui_elements"
                },
                "intent": {
                    "type": "string",
                    "description": "what to click like search field or login button"
                },
                "platform": {
                    "type": "string",
                    "description": "mobile or web"
                }
            },
            "required": [
                "elements",
                "intent",
                "platform"
            ]
        }
    },
    {
        "name": "analyze_screen_for_verification",
        "description": "Analyze screen elements to find best verification for node detection. Returns ready-to-use verification parameters. MCP-formatted response with verification params\n\nExample: analyze_screen_for_verification(elements=[...], node_label='home', platform='web')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "elements": {
                    "type": "array",
                    "description": "elements from dump_ui_elements"
                },
                "node_label": {
                    "type": "string",
                    "description": "node name like home or login"
                },
                "platform": {
                    "type": "string",
                    "description": "mobile or web"
                }
            },
            "required": [
                "elements",
                "node_label",
                "platform"
            ]
        }
    }
]
