"""
Script tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in script_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 2 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for script.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/script_tools.py docstrings
    """
    return [
    {
        "name": "execute_script",
        "description": "Execute a Python script on a device MCP-formatted response with script execution results",
        "inputSchema": {
            "type": "object",
            "properties": {
                "script_name": {
                    "type": "string",
                    "description": "Script filename (e.g., 'my_script.py'"
                },
                "host_name": {
                    "type": "string",
                    "description": "Host where device is located"
                },
                "device_id": {
                    "type": "string",
                    "description": "Device identifier"
                },
                "parameters": {
                    "type": "string",
                    "description": "CLI parameters as string (e.g., '--param1 value1 --param2 value2'"
                }
            },
            "required": [
                "script_name",
                "host_name",
                "device_id"
            ]
        }
    },
    {
        "name": "list_scripts",
        "description": "List all available Python scripts in the scripts directory. MCP-formatted response with list of scripts\n\nExample: list_scripts()",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    }
]
