"""
Testcase tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in testcase_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 6 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for testcase.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/testcase_tools.py docstrings
    """
    return [
    {
        "name": "execute_testcase",
        "description": "Execute a test case by name (or graph for unsaved testcases) \u26a0\ufe0f CRITICAL: Host/Device Selection - If user explicitly specifies host_name/device_id: Use those values directly - Otherwise: Call get_compatible_hosts(userinterface_name='...') FIRST to find compatible hosts - DO NOT use default values blindly without checking compatibility REUSES existing /server/testcase/execute endpoint (same as frontend) Pattern from server_testcase_routes.py line 167 Workflow (when host NOT specified by user): 1. Call get_compatible_hosts(userinterface_name='your_ui') 2. Use recommended host_name and device_id from response 3. Call execute_testcase with those values Workflow (when user specifies host): 1. User says \"use host X with device Y\" 2. Call execute_testcase directly with host_name='X', device_id='Y' MCP-formatted response with execution results",
        "inputSchema": {
            "type": "object",
            "properties": {
                "testcase_name": {
                    "type": "string",
                    "description": "Test case name like 'Login Flow Test'"
                },
                "graph_json": {
                    "type": "object",
                    "description": "For unsaved/temporary testcases only"
                }
            },
            "required": [
                "testcase_name"
            ]
        }
    },
    {
        "name": "execute_testcase_by_id",
        "description": "LEGACY WRAPPER: Load and execute a saved test case by ID \u26a0\ufe0f DEPRECATED: Use execute_testcase(testcase_name=...) instead This wrapper is kept for backward compatibility with existing MCP clients. MCP-formatted response with execution results",
        "inputSchema": {
            "type": "object",
            "properties": {
                "userinterface_name": {
                    "type": "string",
                    "description": "Override interface (if empty, uses testcase's interface"
                }
            },
            "required": []
        }
    },
    {
        "name": "list_testcases",
        "description": "List all saved test cases. MCP-formatted response with list of test cases\n\nExample: list_testcases()",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    },
    {
        "name": "load_testcase",
        "description": "Load a saved test case by ID. MCP-formatted response with test case graph\n\nExample: load_testcase(testcase_id='abc123')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "testcase_id": {
                    "type": "string",
                    "description": "test case ID to load"
                }
            },
            "required": [
                "testcase_id"
            ]
        }
    },
    {
        "name": "rename_testcase",
        "description": "Rename an existing test case USES /server/testcase/save endpoint with testcase_id for update Pattern from server_testcase_routes.py line 28 (update path) MCP-formatted response with rename result",
        "inputSchema": {
            "type": "object",
            "properties": {
                "testcase_id": {
                    "type": "string",
                    "description": "Test case UUID to rename"
                },
                "new_name": {
                    "type": "string",
                    "description": "New testcase name"
                }
            },
            "required": [
                "testcase_id",
                "new_name"
            ]
        }
    },
    {
        "name": "save_testcase",
        "description": "Save a test case graph to the database REUSES existing /server/testcase/save endpoint (same as frontend) Pattern from server_testcase_routes.py line 28 MCP-formatted response with saved testcase info",
        "inputSchema": {
            "type": "object",
            "properties": {
                "testcase_name": {
                    "type": "string",
                    "description": "Name for the test case"
                },
                "graph_json": {
                    "type": "object",
                    "description": "Graph from generate_test_graph"
                },
                "folder": {
                    "type": "string",
                    "description": "Folder path like 'smoke_tests'"
                }
            },
            "required": [
                "testcase_name",
                "graph_json"
            ]
        }
    }
]
