"""
Transcript tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in transcript_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 1 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for transcript.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/transcript_tools.py docstrings
    """
    return [
    {
        "name": "get_transcript",
        "description": "Get audio transcript from device Fetches Whisper-generated transcripts with optional translation. MCP-formatted response with transcript segments and timestamps",
        "inputSchema": {
            "type": "object",
            "properties": {
                "target_language": {
                    "type": "string",
                    "description": "For translation (e.g., 'fr', 'es'"
                }
            },
            "required": []
        }
    }
]
