"""
Tree tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in tree_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 10 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for tree.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/tree_tools.py docstrings
    """
    return [
    {
        "name": "create_edge",
        "description": "Create an edge between two nodes Created edge object\n\nExample: create_edge(tree_id='abc', source_node_id='home', target_node_id='settings', source_label='home', target_label='settings', action_sets=[...])",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "source_node_id": {
                    "type": "string",
                    "description": "source node ID"
                },
                "target_node_id": {
                    "type": "string",
                    "description": "target node ID"
                },
                "source_label": {
                    "type": "string",
                    "description": "source node label"
                },
                "target_label": {
                    "type": "string",
                    "description": "target node label"
                },
                "action_sets": {
                    "type": "array",
                    "description": "array of action sets with bidirectional actions"
                }
            },
            "required": [
                "tree_id",
                "source_node_id",
                "target_node_id",
                "source_label",
                "target_label",
                "action_sets"
            ]
        }
    },
    {
        "name": "create_node",
        "description": "Create a node in navigation tree. Remember to add verifications and test them after creation. Created node object\n\nExample: create_node(tree_id='abc', node_id='home', label='Home Screen')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "node_id": {
                    "type": "string",
                    "description": "node identifier auto-generated if omitted"
                },
                "label": {
                    "type": "string",
                    "description": "node label or name"
                },
                "type": {
                    "type": "string",
                    "description": "node type default screen"
                },
                "position": {
                    "type": "object",
                    "description": "x y coordinates"
                },
                "data": {
                    "type": "object",
                    "description": "custom metadata"
                }
            },
            "required": [
                "tree_id",
                "label"
            ]
        }
    },
    {
        "name": "create_subtree",
        "description": "Create a subtree for a parent node. Created subtree with new tree_id\n\nExample: create_subtree(parent_tree_id='abc', parent_node_id='menu', subtree_name='Menu Options')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "parent_tree_id": {
                    "type": "string",
                    "description": "parent tree ID"
                },
                "parent_node_id": {
                    "type": "string",
                    "description": "parent node ID to attach subtree"
                },
                "subtree_name": {
                    "type": "string",
                    "description": "name for the subtree"
                }
            },
            "required": [
                "parent_tree_id",
                "parent_node_id",
                "subtree_name"
            ]
        }
    },
    {
        "name": "delete_edge",
        "description": "Delete an edge from navigation tree. Success confirmation\n\nExample: delete_edge(tree_id='abc', edge_id='edge1')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "edge_id": {
                    "type": "string",
                    "description": "edge identifier to delete"
                }
            },
            "required": [
                "tree_id",
                "edge_id"
            ]
        }
    },
    {
        "name": "delete_node",
        "description": "Delete a node from navigation tree. Success confirmation\n\nExample: delete_node(tree_id='abc', node_id='home')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "node_id": {
                    "type": "string",
                    "description": "node identifier to delete"
                }
            },
            "required": [
                "tree_id",
                "node_id"
            ]
        }
    },
    {
        "name": "get_edge",
        "description": "Get a specific edge by ID. Full edge object with all fields\n\nExample: get_edge(tree_id='abc', edge_id='edge1')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "edge_id": {
                    "type": "string",
                    "description": "edge identifier"
                }
            },
            "required": [
                "tree_id",
                "edge_id"
            ]
        }
    },
    {
        "name": "get_node",
        "description": "Get a specific node by ID. Full node object with all fields\n\nExample: get_node(tree_id='abc', node_id='home')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "node_id": {
                    "type": "string",
                    "description": "node identifier"
                }
            },
            "required": [
                "tree_id",
                "node_id"
            ]
        }
    },
    {
        "name": "save_node_screenshot",
        "description": "Take screenshot and save it to a specific node. Wraps screenshot capture and node update into single operation. Success with screenshot URL and node ID\n\nExample: save_node_screenshot(tree_id='abc', node_id='home', label='Home Screen', host_name='sunri-pi1', device_id='device1', userinterface_name='google_tv')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "node_id": {
                    "type": "string",
                    "description": "node identifier to attach screenshot"
                },
                "label": {
                    "type": "string",
                    "description": "node label used as filename"
                },
                "host_name": {
                    "type": "string",
                    "description": "host where device is connected"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "interface name for organizing screenshots"
                }
            },
            "required": [
                "tree_id",
                "node_id",
                "label",
                "host_name",
                "device_id",
                "userinterface_name"
            ]
        }
    },
    {
        "name": "update_edge",
        "description": "Update an existing edge's actions. Must use same format as create_edge. Updated edge object\n\nExample: update_edge(tree_id='abc', edge_id='edge1', action_sets=[...])",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "edge_id": {
                    "type": "string",
                    "description": "edge identifier to update"
                },
                "action_sets": {
                    "type": "array",
                    "description": "new action sets to replace existing"
                }
            },
            "required": [
                "tree_id",
                "edge_id",
                "action_sets"
            ]
        }
    },
    {
        "name": "update_node",
        "description": "Update an existing node. Verifications in updates will be validated against available device controllers. Updated node object\n\nExample: update_node(tree_id='abc', node_id='home', updates={'label': 'Home Screen New'})",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "node_id": {
                    "type": "string",
                    "description": "node identifier to update"
                },
                "updates": {
                    "type": "object",
                    "description": "fields to update like label position type or data"
                }
            },
            "required": [
                "tree_id",
                "node_id",
                "updates"
            ]
        }
    }
]
