"""
Userinterface tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in userinterface_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 6 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for userinterface.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/userinterface_tools.py docstrings
    """
    return [
    {
        "name": "create_userinterface",
        "description": "Create a new userinterface (app model). Created userinterface with root tree info\n\nExample: create_userinterface(name='netflix_android', device_model='android_tv')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "interface name like netflix_android"
                },
                "device_model": {
                    "type": "string",
                    "description": "device model like android_tv or web"
                },
                "description": {
                    "type": "string",
                    "description": "optional description"
                }
            },
            "required": [
                "name",
                "device_model"
            ]
        }
    },
    {
        "name": "delete_userinterface",
        "description": "Delete a userinterface (soft delete). DESTRUCTIVE OPERATION - requires explicit confirmation. Success confirmation\n\nExample: delete_userinterface(userinterface_id='abc123', confirm=true)",
        "inputSchema": {
            "type": "object",
            "properties": {
                "userinterface_id": {
                    "type": "string",
                    "description": "UUID to delete"
                },
                "confirm": {
                    "type": "boolean",
                    "description": "must be true to proceed as safety check"
                }
            },
            "required": [
                "userinterface_id",
                "confirm"
            ]
        }
    },
    {
        "name": "get_userinterface_complete",
        "description": "Get complete userinterface with ALL nodes, edges, subtrees, and metrics. Accepts EITHER userinterface_id OR userinterface_name. Complete tree structure with nodes, edges, subtrees, metrics\n\nExample: get_userinterface_complete(userinterface_name='google_tv')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "userinterface_id": {
                    "type": "string",
                    "description": "UUID if not using name"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "name if not using ID"
                },
                "include_metrics": {
                    "type": "boolean",
                    "description": "include metrics data default true"
                }
            },
            "required": []
        }
    },
    {
        "name": "list_edges",
        "description": "List all edges in a navigation tree. List of edges with action sets\n\nExample: list_edges(tree_id='abc123')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "node_ids": {
                    "type": "array",
                    "description": "filter by node IDs"
                }
            },
            "required": [
                "tree_id"
            ]
        }
    },
    {
        "name": "list_nodes",
        "description": "List all nodes in a navigation tree. List of nodes with details\n\nExample: list_nodes(tree_id='abc123')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "page": {
                    "type": "integer",
                    "description": "page number default 0"
                },
                "limit": {
                    "type": "integer",
                    "description": "results per page default 100"
                }
            },
            "required": [
                "tree_id"
            ]
        }
    },
    {
        "name": "list_userinterfaces",
        "description": "List all userinterfaces. MCP-formatted response with list of interfaces\n\nExample: list_userinterfaces()",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    }
]
