"""
Verification tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in verification_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 3 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for verification.
    
    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/verification_tools.py docstrings
    """
    return [
    {
        "name": "dump_ui_elements",
        "description": "Dump UI elements from current device screen REUSES existing verification endpoints MCP-formatted response with UI elements array",
        "inputSchema": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "description": "defaults to 'device1'"
                },
                "host_name": {
                    "type": "string",
                    "description": "defaults to 'sunri-pi1'"
                },
                "platform": {
                    "type": "string",
                    "description": "'mobile', 'web', 'tv'"
                }
            },
            "required": []
        }
    },
    {
        "name": "list_verifications",
        "description": "List available verification types for a device. MCP-formatted response with categorized list of available verifications\n\nExample: list_verifications(host_name='sunri-pi1', device_id='device1')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "host_name": {
                    "type": "string",
                    "description": "host name where device is connected"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                }
            },
            "required": [
                "host_name",
                "device_id"
            ]
        }
    },
    {
        "name": "verify_node",
        "description": "Execute verifications for a specific node. Runs embedded verifications using executeBatch endpoint. Verification results with pass/fail status verify_node({ \"node_id\": \"home\", \"tree_id\": \"ae9147a0-07eb-44d9-be71-aeffa3549ee0\", \"userinterface_name\": \"netflix_mobile\" })\n\nExample: verify_node(node_id='home', tree_id='abc', userinterface_name='google_tv')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "node_id": {
                    "type": "string",
                    "description": "node identifier"
                },
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "user interface name"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                },
                "host_name": {
                    "type": "string",
                    "description": "host name where device is connected"
                }
            },
            "required": [
                "node_id",
                "tree_id",
                "userinterface_name"
            ]
        }
    }
]
