name: alert-triage
version: 1.1.0
description: Classify and route alerts

triggers:
  - triage alert
  - classify alert
  - new alert

system_prompt: |
  Triage incoming alerts by severity.
  
  CLASSIFICATION:
  - Critical: Immediate response needed
  - High: Response in 15 min
  - Medium: Response in 1 hour
  - Low: Log and monitor
  
  FALSE POSITIVE INDICATORS:
  - Alert cleared within seconds
  - Known maintenance window
  - Test environment

tools:
  - get_device_info
  - capture_screenshot

platform: null
requires_device: false
timeout_seconds: 120
