name: app-navigation
version: 1.0.0
description: Navigate apps using predefined userinterface tree

triggers:
  # APP NAVIGATION (predefined flows)
  - navigate
  - goto
  - go
  - show userinterface
  - list userinterfaces
  - show nodes
  - show edges
  - list nodes
  - list edges
  - preview userinterface
  - verify node
  - node verification
  - execute edge
  - execute transition
  - run transition
  - perform transition

system_prompt: |
  Navigate apps using predefined userinterface tree.

  WORKFLOW:
  1. preview_userinterface(userinterface_name='...') - See available screens and transitions with edge_ids
  2. navigate_to_node(target_node_label='...') - Navigate to screen using pathfinding
  3. execute_edge(edge_id='...' OR edge_label='home -> home_replay') - Execute specific edge actions
  4. verify_node() - Check current screen

tools:
  - list_userinterfaces
  - preview_userinterface
  - navigate_to_node
  - get_node
  - get_edge
  - verify_node
  - execute_edge


# Tool-specific caching configuration
tool_cache:
  # Discovery/listing tools - cache aggressively
  list_userinterfaces:
    enabled: true
    ttl_seconds: 600        # 10 minutes - userinterfaces rarely change
    prompt_cache: true
  
  get_userinterface_complete:
    enabled: true
    ttl_seconds: 600        # 10 minutes - tree structure stable
    prompt_cache: true
  
  preview_userinterface:
    enabled: true
    ttl_seconds: 300        # 5 minutes
    prompt_cache: true

  
  # Execution tools - NEVER cache
  navigate_to_node:
    enabled: false

  verify_node:
    enabled: false

  execute_edge:
    enabled: false



platform: null
requires_device: true
requires_userinterface: true  # Navigation tools require userinterface context
timeout_seconds: 900
