name: control-device
version: 1.0.0
description: Control a device to navigate, act, and verify nodes

triggers:
  - control device
  - navigate node
  - execute device action
  - verify node
  - list hosts
  - list devices
  - show devices
  - device info
  - list userinterfaces

system_prompt: |
  CONTROL DEVICE WORKFLOW
  1) get_device_info() → list all hosts and devices with full details (host_name, device_id, device_model, status)
  2) list_userinterfaces() → list available userinterfaces/apps
  3) get_userinterface_complete(userinterface_name) → get complete userinterface tree structure
  4) get_compatible_hosts(userinterface_name) → choose host_name/device_id for a userinterface
  5) take_control(host_name, device_id) before any navigation/actions
  6) navigate_to_node(tree_id, userinterface_name, target_node_label) for pathfinding
  7) execute_device_action(actions=[...]) for directional or manual steps
  8) verify_node(node_id, tree_id, userinterface_name, host_name) to validate state
  9) release_control(host_name, device_id) when done

tools:
  - get_device_info
  - list_userinterfaces
  - get_userinterface_complete
  - get_compatible_hosts
  - take_control
  - navigate_to_node
  - execute_device_action
  - verify_node
  - release_control

platform: null
requires_device: true
timeout_seconds: 1800


