name: control-device
version: 1.0.0
description: Control a device to navigate, act, and verify nodes

triggers:
  - control device
  - navigate node
  - execute device action
  - verify node

system_prompt: |
  CONTROL DEVICE WORKFLOW
  1) get_compatible_hosts(userinterface_name) → choose host_name/device_id
  2) take_control(host_name, device_id) before any navigation/actions
  3) navigate_to_node(tree_id, userinterface_name, target_node_label) for pathfinding
  4) execute_device_action(actions=[...]) for directional or manual steps
  5) verify_node(node_id, tree_id, userinterface_name, host_name) to validate state
  6) release_control(host_name, device_id) when done

tools:
  - get_compatible_hosts
  - take_control
  - navigate_to_node
  - execute_device_action
  - verify_node
  - release_control

platform: null
requires_device: true
timeout_seconds: 1800


