name: control-device
version: 1.0.0
description: Control a device to navigate, act, and verify nodes

triggers:
  - control device
  - navigate device to node
  - device navigation
  - go to node on device
  - navigate app screen
  - navigate to screen
  - execute device action
  - verify device node
  - list hosts
  - list devices
  - show devices
  - device info
  - device status
  - list userinterfaces
  - list apps

system_prompt: |
  DEVICE CONTROL & NODE NAVIGATION
  Control physical devices (phones, TVs) and navigate APP SCREENS.
  
  SCOPE: Device/app screens (Netflix home, Settings). NOT for frontend pages.
  
  WORKFLOW:
  1) get_device_info() - List available devices
  2) list_userinterfaces() - Find available interfaces
  3) get_userinterface_complete() - Get tree_id and nodes/edges
  4) get_compatible_hosts() - Get host_name and device_id
  5) take_control → navigate_to_node → execute_device_action → verify_node → release_control

tools:
  - get_device_info
  - list_userinterfaces
  - get_userinterface_complete
  - get_compatible_hosts
  - take_control
  - navigate_to_node
  - execute_device_action
  - verify_node
  - release_control

platform: null
requires_device: true
timeout_seconds: 1800


