name: control-device
version: 1.0.0
description: Control devices with direct hardware actions

triggers:
  # DEVICE CONTROL (direct hardware actions)
  - control device
  - execute device action
  - device action
  - click on device
  - click element on device
  - tap on device
  - swipe on device
  - swipe up on device
  - swipe down on device
  - swipe left on device
  - swipe right on device
  - press button on device
  - press key on device
  - device control
  - hardware action
  - button press
  - device interaction
  - interact with device
  - device swipe
  - device click
  - device press
  - device tap

  # DEVICE DISCOVERY
  - available actions
  - device actions

system_prompt: |
  Control physical devices with raw hardware actions (click, swipe, press).
  NOT for predefined navigation flows (that's app-navigation skill).

  WORKFLOW:
  1. get_device_info() → find available devices
  2. list_actions() → see valid actions for the device
  3. execute_device_action() → use ONLY actions from step 2, match parameters exactly

tools:
  - get_device_info
  - list_actions
  - execute_device_action
  - dump_ui_elements

platform: null
requires_device: true
timeout_seconds: 1800


