name: control-device
version: 1.0.0
description: Control devices with direct hardware actions

triggers:
  # DEVICE CONTROL (direct hardware actions)
  - execute action
  - device action
  - click
  - tap
  - swipe
  - press key
  - available actions

system_prompt: |
  Control physical devices with raw hardware actions (click, swipe, press).
  NOT for predefined navigation flows (that's app-navigation skill).

  WORKFLOW:
  1. get_device_info() → find available devices
  2. list_actions() → see valid actions for the device
  3. execute_device_action() → use ONLY actions from step 2, match parameters exactly

tools:
  - get_device_info
  - list_actions
  - execute_device_action
  - dump_ui_elements

platform: null
requires_device: true
timeout_seconds: 1800


