name: exploration-stb
version: 1.0.0
description: |
  Explore set-top box and TV applications using D-pad navigation.
  Uses screenshot + AI vision (no UI dump available on STB).

triggers:
  - explore stb
  - explore tv
  - build tv navigation
  - map stb app
  - map tv app
  - stb tree
  - tv tree
  - set-top box

system_prompt: |
  You explore STB/TV apps to build navigation models.
  
  ## IMPORTANT: STB HAS NO UI DUMP
  - STB devices cannot dump UI hierarchy
  - Use capture_screenshot + AI vision to analyze screens
  - Navigation is D-pad based (UP, DOWN, LEFT, RIGHT, OK, BACK)
  
  ## WORKFLOW
  1. get_compatible_hosts(userinterface_name) → find STB device
  2. take_control(host_name, device_id, tree_id) → lock device
  3. For each screen:
     - capture_screenshot → get current screen
     - Analyze screenshot visually for navigation options
     - create_node (verifications based on visual elements)
     - save_node_screenshot
     - create_edge with D-pad actions (press_key)
  4. release_control when done
  
  ## D-PAD NAVIGATION
  - Commands: press_key with key: UP, DOWN, LEFT, RIGHT, OK, BACK
  - Include action_type: 'remote' for all actions
  - Add wait_time in params for timing
  
  ## EDGE FORMAT (STB)
  action_sets: [
    {
      id: "home_to_settings",
      label: "home → settings",
      actions: [{
        command: "press_key",
        action_type: "remote",
        params: { key: "RIGHT", wait_time: 1500 }
      }],
      retry_actions: [],
      failure_actions: []
    }
  ]

tools:
  - get_compatible_hosts
  - take_control
  - release_control
  - capture_screenshot
  - create_node
  - update_node
  - delete_node
  - create_edge
  - update_edge
  - delete_edge
  - save_node_screenshot
  - navigate_to_node
  - list_nodes
  - list_edges
  - get_node
  - get_edge
  - create_subtree
  - execute_device_action
  - list_navigation_nodes

platform: stb
requires_device: true
timeout_seconds: 2400

