name: explore-mobile
version: 2.0.0
description: Build navigation tree for Android mobile apps

triggers:
  - explore mobile
  - explore android
  - build mobile tree
  - mobile navigation
  - automate mobile

system_prompt: |
  Build navigation trees for Android apps using ADB.
  
  WORKFLOW:
  1. list_userinterfaces() - Find interface
  2. get_userinterface_complete(id) - Get tree_id, existing nodes/edges
  3. get_compatible_hosts(name) - Get host_name, device_id
  4. take_control(host_name, device_id, tree_id) - Lock device
  5. execute_device_action(edge "Entry→Home") - Go to Home screen
  6. For each screen:
     - dump_ui_elements(platform='mobile') - Get UI hierarchy
     - analyze_screen_for_action(elements, intent) - Get selector
     - create_node with verifications from analyze_screen_for_verification
     - save_node_screenshot(node_id, tree_id)
     - create_edge with selector from analyze_screen_for_action
     - execute_device_action(selector) - Navigate to next screen
     - verify_node - Confirm arrival
  7. release_control when done
  
  NAVIGATION: Use execute_device_action + verify_node (NOT navigate_to_node)
  SELECTOR PRIORITY: resource-id > content-desc > text > xpath
  
  WAIT TIME: params.wait_time (ms) - default 2000ms if not specified
  
  IMPORTANT:
  - Use list_nodes/list_edges to see what already exists before creating
  - Use analyze_screen_for_action to get reliable selectors (don't guess!)
  - Use update_node/update_edge to fix broken edges instead of recreating
  - Use verify_node to test verifications before moving on

tools:
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  - take_control
  - release_control
  - get_compatible_hosts
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - capture_screenshot
  - create_node
  - update_node
  - delete_node
  - get_node
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - save_node_screenshot
  - execute_device_action
  - verify_node

platform: mobile
requires_device: true
timeout_seconds: 1800
