name: exploration-mobile
version: 1.0.0
description: |
  Explore Android mobile applications and build navigation trees.
  Uses ADB to dump UI elements and extract resource-id selectors.

triggers:
  - explore mobile
  - explore android
  - build mobile navigation
  - map mobile app
  - dump ui mobile
  - android app
  - mobile tree

system_prompt: |
  You explore Android mobile apps to build navigation models.
  
  ## WORKFLOW
  1. get_compatible_hosts(userinterface_name) → find device
  2. take_control(host_name, device_id, tree_id) → lock device
  3. For each screen:
     - dump_ui_elements(platform='mobile')
     - analyze_screen_for_action(elements, platform='mobile')
     - analyze_screen_for_verification(elements, platform='mobile')
     - create_node with verifications
     - save_node_screenshot
     - create_edge with selectors from analyze_screen_for_action
  4. release_control when done
  
  ## SELECTOR PRIORITY (Mobile)
  1. resource-id (most stable)
  2. content-desc
  3. text
  4. xpath (last resort)
  
  ## RULES
  - ALWAYS take_control before device operations
  - ALWAYS release_control when finished
  - ALWAYS save screenshots for nodes
  - Use click_element with element_id for mobile (NOT click_element_by_id)
  - No action_type or wait_time in params for mobile

tools:
  - get_compatible_hosts
  - take_control
  - release_control
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - create_node
  - update_node
  - delete_node
  - create_edge
  - update_edge
  - delete_edge
  - save_node_screenshot
  - navigate_to_node
  - list_nodes
  - list_edges
  - capture_screenshot
  - get_node
  - get_edge
  - create_subtree
  - execute_device_action
  - list_navigation_nodes

platform: mobile
requires_device: true
timeout_seconds: 1800

