name: explore-mobile
version: 4.0.0
description: Build navigation tree for mobile apps with auto-validation

triggers:
  - explore mobile
  - explore android
  - build mobile tree

system_prompt: |
  Build navigation trees for mobile apps. auto_discover_screen includes validation.
  
  SETUP:
  1. list_userinterfaces() - Find interface
  2. get_userinterface_complete() - Get tree_id, existing nodes/edges
  3. get_compatible_hosts() - Get host_name and device_id
  4. take_control() - Lock device
  5. navigate_to_node(target_node_label="home")
  
  PHASE 1 - DISCOVER & VALIDATE (automatic):
  auto_discover_screen(tree_id, host_name, userinterface_name)
  → Creates nodes/edges
  → AUTOMATICALLY validates each edge (forward + backward)
  → Returns validation results including FAILED_ITEMS
  
  PHASE 2 - FIX FAILURES ONLY (if any):
  Check the 'failed_items' in auto_discover_screen response.
  
  If there are failures:
  1. dump_ui_elements() - See current screen state
  2. For each failed edge:
     - If forward failed: analyze_screen_for_action() to find correct selector
     - If backward failed: check if 2x BACK needed (keyboard screens)
  3. update_edge() to fix the edge actions
  4. Optionally: execute_device_action() to test the fix
  
  ⚠️ KEYBOARD SCREENS: Need 2x BACK
  When backward validation fails, update_edge with iterator:2:
  ```
  update_edge(
    tree_id=..., edge_id=...,
    action_sets=[
      {...forward...},
      {"id": "x_to_home", "label": "x → home",
       "actions": [{"command": "press_key", "params": {"key": "BACK"}, "iterator": 2}],
       "retry_actions": [], "failure_actions": []}
    ]
  )
  ```
  
  PHASE 3 - SCREENSHOTS (optional, for nodes without them):
  For nodes that need screenshots:
  - navigate_to_node(target_node_label="...")
  - save_node_screenshot(...)
  
  CLEANUP:
  release_control

tools:
  - navigate_to_node
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  - take_control
  - release_control
  - get_compatible_hosts
  - auto_discover_screen
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - create_node
  - update_node
  - delete_node
  - get_node
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - save_node_screenshot
  - execute_device_action
  - verify_node

platform: mobile
requires_device: true
timeout_seconds: 1800
