name: explore-mobile
version: 2.0.0
description: Build navigation tree for Android mobile apps

triggers:
  - explore mobile
  - explore android
  - build mobile tree
  - mobile navigation
  - automate mobile

system_prompt: |
  Build navigation trees for Android apps using ADB.
  
  WORKFLOW:
  1. list_userinterfaces() - Find available interfaces
  2. get_userinterface_complete(userinterface_id) - Get tree_id and existing nodes/edges
  3. get_compatible_hosts(userinterface_name) - Get host_name and device_id
  4. take_control(host_name, device_id, tree_id) - Lock device and build cache
  5. For each screen:
     - dump_ui_elements(platform='mobile') - Get current UI hierarchy
     - analyze_screen_for_action(elements, intent, platform='mobile') - Get best selector
     - create_node or update_node with verifications
     - save_node_screenshot(node_id, tree_id)
     - create_edge or update_edge with selectors from analyze_screen_for_action
     - execute_device_action to test the action works
     - navigate_to_node to move around
  6. verify_node to test verifications work
  7. release_control when done
  
  SELECTOR PRIORITY: resource-id > content-desc > text > xpath
  
  IMPORTANT:
  - Use list_nodes/list_edges to see what already exists before creating
  - Use analyze_screen_for_action to get reliable selectors (don't guess!)
  - Use update_node/update_edge to fix broken edges instead of recreating
  - Use verify_node to test verifications before moving on

tools:
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  - take_control
  - release_control
  - navigate_to_node
  - get_device_info
  - get_compatible_hosts

  - analyze_screen_for_action
  - analyze_screen_for_verification
  - capture_screenshot
  - create_node
  - update_node
  - delete_node
  - get_node
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - save_node_screenshot
  - execute_device_action
  - list_actions
  - list_verifications
  - verify_node

platform: mobile
requires_device: true
timeout_seconds: 1800
