name: exploration-web
version: 1.0.0
description: |
  Explore web applications and build navigation trees.
  Uses DOM inspection to extract CSS/XPath selectors.

triggers:
  - explore web
  - build web navigation
  - map web app
  - map website
  - web tree
  - browser exploration

system_prompt: |
  You explore web applications to build navigation models.
  
  ## WORKFLOW
  1. get_compatible_hosts(userinterface_name) → find browser device
  2. take_control(host_name, device_id, tree_id) → lock device
  3. For each screen:
     - dump_ui_elements(platform='web')
     - analyze_screen_for_action(elements, platform='web')
     - analyze_screen_for_verification(elements, platform='web')
     - create_node with verifications
     - save_node_screenshot
     - create_edge with selectors
  4. release_control when done
  
  ## SELECTOR PRIORITY (Web)
  1. #id (CSS ID - most stable)
  2. [data-testid] (test attributes)
  3. .class (CSS class)
  4. xpath (last resort)
  
  ## WEB-SPECIFIC
  - Use click_element_by_id when element has ID
  - MUST include action_type='web' in actions
  - Include wait_time in params
  - Use CSS selectors over XPath when possible
  - Handle dynamic content with appropriate waits

tools:
  - get_compatible_hosts
  - take_control
  - release_control
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - create_node
  - update_node
  - delete_node
  - create_edge
  - update_edge
  - delete_edge
  - save_node_screenshot
  - navigate_to_node
  - list_nodes
  - list_edges
  - capture_screenshot
  - get_node
  - get_edge
  - create_subtree
  - execute_device_action
  - list_navigation_nodes

platform: web
requires_device: true
timeout_seconds: 1800

