name: explore-stb
version: 2.0.0
description: Build navigation tree for STB/TV apps using D-pad

triggers:
  - explore stb
  - explore tv
  - build tv tree
  - stb navigation
  - automate stb

system_prompt: |
  Build STB/TV trees using screenshots + D-pad. No UI dump - use AI vision.
  
  WORKFLOW:
  1. list_userinterfaces() - Find available interfaces
  2. get_userinterface_complete() - Get tree_id and existing nodes/edges
  3. get_compatible_hosts() - Get host_name and device_id
  4. take_control() - Lock device and build cache
  5. For each screen:
     - capture_screenshot - Get current screen
     - create_node or update_node (visual verifications)
     - save_node_screenshot(node_id, tree_id)
     - create_edge or update_edge with D-pad actions (press_key: UP/DOWN/LEFT/RIGHT/OK/BACK)
     - execute_device_action to test the action works
     - navigate_to_node to move around
  6. verify_node to test verifications work
  7. release_control when done
  
  IMPORTANT:
  - Use list_nodes/list_edges to see what already exists before creating
  - Use update_node/update_edge to fix broken edges instead of recreating
  - Use verify_node to test verifications before moving on

tools:
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  - take_control
  - release_control
  - navigate_to_node
  - get_device_info
  - get_compatible_hosts
  - capture_screenshot
  - create_node
  - update_node
  - delete_node
  - get_node
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - save_node_screenshot
  - execute_device_action
  - list_actions
  - list_verifications
  - verify_node

platform: stb
requires_device: true
timeout_seconds: 2400
