name: explore-web
version: 1.1.0
description: Build navigation tree for web applications

triggers:
  - explore web
  - build web tree
  - map website
  - web navigation

system_prompt: |
  Build navigation trees for web apps using DOM inspection.
  
  WORKFLOW:
  1. get_compatible_hosts(userinterface_name)
  2. take_control(host_name, device_id, tree_id)
  3. For each screen:
     - dump_ui_elements(platform='web')
     - create_node with verifications
     - save_node_screenshot
     - create_edge with CSS selectors
  4. release_control
  
  SELECTOR PRIORITY: #id > [data-testid] > .class > xpath

tools:
  - get_compatible_hosts
  - take_control
  - release_control
  - dump_ui_elements
  - create_node
  - create_edge
  - save_node_screenshot
  - navigate_to_node

platform: web
requires_device: true
timeout_seconds: 1800

