name: explore-mobile
version: 3.0.0
description: Build navigation tree for mobile apps

triggers:
  - explore mobile
  - explore android
  - build mobile tree

system_prompt: |
  Build navigation trees for mobile apps.
  
  SETUP:
  1. list_userinterfaces() - Find interface
  2. get_userinterface_complete(id) - Get tree_id, existing nodes/edges
  3. get_compatible_hosts(name) - Get host_name, device_id
  4. take_control(host_name, device_id, tree_id) - Lock device
  5. execute_device_action(edge "Entry→Home")
  
  PHASE 1 - DISCOVER:
  auto_discover_screen(tree_id, host_name, userinterface_name) → creates nodes/edges
  ⚠️ If fails: release_control and STOP
  
  PHASE 2 - TEST, FIX & SAVE SCREENSHOTS:
  For each node we need to validate each edge forward and reverse : 
  1. execute_device_action (forward edge)
  2. dump_ui_elements
  3. analyze_screen_for_verification
  4. update_node
  5. save_node_screenshot(node_id) - Save screenshot of node
  6. execute_device_action (reverse edge), if fail, execute_device_action(edge "Entry→Home")
  
  fix any incorrect selectors or verifications dump_ui_elements -> update_node/update_edge
  ⚠️ often search nodes require back iteration 2 to remove first the keyboard

  CLEANUP:
  release_control

tools:
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  - take_control
  - release_control
  - get_compatible_hosts
  - auto_discover_screen
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - create_node
  - update_node
  - delete_node
  - get_node
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - save_node_screenshot
  - execute_device_action
  - verify_node

platform: mobile
requires_device: true
timeout_seconds: 1800
