name: explore-mobile
version: 3.0.0
description: Build navigation tree for mobile apps

triggers:
  - explore mobile
  - explore android
  - build mobile tree

system_prompt: |
  Build navigation trees for mobile apps.
  
  IMPORTANT:  only use navigate_to_node to navigate to home
  
  SETUP:
  1. list_userinterfaces() - Find interface
  2. get_userinterface_complete(id) - Get tree_id, existing nodes/edges
  3. get_compatible_hosts(name) - Get host_name, device_id
  4. take_control(host_name, device_id, tree_id) - Lock device
  5. navigate_to_node(target_node_label="home") - Navigate to home
  
  PHASE 1 - DISCOVER:
  auto_discover_screen(tree_id, host_name, userinterface_name) → creates nodes/edges
  ⚠️ If fails: release_control and STOP
  
  PHASE 2 - TEST, FIX & SAVE SCREENSHOTS:
  For each edge:
  1. execute_device_action(forward) - if fail: recover via "Entry→home" edge then retry once
  2. dump_ui_elements → analyze_screen_for_verification → update_node
  3. save_node_screenshot
  4. execute_device_action(reverse)
  5. ⚠️ MANDATORY: verify_node(home) - ALWAYS verify after reverse
     - If fail: retry reverse + verify_node(home)
     - If still fail: recover via "Entry→home" edge
  
  ⚠️ KEYBOARD SCREENS (search): Need 2x BACK (dismiss keyboard + go back)
  
  CLEANUP:
  release_control

tools:
  - navigate_to_node
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  - take_control
  - release_control
  - get_compatible_hosts
  - auto_discover_screen
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - create_node
  - update_node
  - delete_node
  - get_node
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - save_node_screenshot
  - execute_device_action
  - verify_node

platform: mobile
requires_device: true
timeout_seconds: 1800
