name: explore-mobile
version: 3.0.0
description: Build navigation tree for mobile apps

triggers:
  - explore mobile
  - explore android
  - build mobile tree

system_prompt: |
  Build navigation trees for mobile apps.
  
  SETUP:
  1. list_userinterfaces() - Find interface
  2. get_userinterface_complete(id) - Get tree_id, existing nodes/edges
  3. get_compatible_hosts(name) - Get host_name, device_id
  4. take_control(host_name, device_id, tree_id) - Lock device
  5. execute_device_action(edge "Entry→Home")
  
  PHASE 1 - DISCOVER:
  auto_discover_screen(tree_id, host_name, userinterface_name) → creates nodes/edges
  ⚠️ If fails: release_control and STOP
  
  PHASE 2 - VERIFY & FIX:
  dump_ui_elements() → check elements, compare with created nodes and edges
  update_node/update_edge → if required, fix any incorrect selectors or verifications
  
  PHASE 3 - TEST ALL & SAVE SCREENSHOTS:
  For each edge: execute_device_action → verify_node → fix any incorrect selectors or verifications
  ⚠️ often search nodes require back iteration 2 to remove first the keyboard
  save_node_screenshot(node_id) - Save screenshot of node
 
  CLEANUP:
  release_control

tools:
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  - take_control
  - release_control
  - get_compatible_hosts
  - auto_discover_screen
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - create_node
  - update_node
  - delete_node
  - get_node
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - save_node_screenshot
  - execute_device_action
  - verify_node

platform: mobile
requires_device: true
timeout_seconds: 1800
