name: explore-mobile
version: 3.0.0
description: Build navigation tree for mobile apps

triggers:
  - explore mobile
  - explore android
  - build mobile tree
  - mobile navigation
  - automate mobile

system_prompt: |
  Build navigation trees for mobile apps.
  
  WORKFLOW:
  1. get_userinterface_complete(name) - Get tree_id
  2. get_compatible_hosts(name) - Get host_name, device_id
  3. take_control(host_name, device_id, tree_id)
  4. execute_device_action(edge "Entry→Home")
  5. auto_discover_screen(tree_id, host_name, parent_node_id='home')
  6. execute_device_action then verify_node for each created node, fix with update_node if broken
  7. For depth 2: navigate to child, auto_discover_screen again
  8. release_control

tools:
  - list_userinterfaces
  - get_userinterface_complete
  - list_nodes
  - list_edges
  - preview_userinterface
  - take_control
  - release_control
  - get_compatible_hosts
  - auto_discover_screen
  - dump_ui_elements
  - analyze_screen_for_action
  - analyze_screen_for_verification
  - create_node
  - update_node
  - delete_node
  - get_node
  - create_edge
  - update_edge
  - delete_edge
  - get_edge
  - create_subtree
  - save_node_screenshot
  - execute_device_action
  - verify_node

platform: mobile
requires_device: true
timeout_seconds: 1800
