name: generate-report
version: 1.0.0
description: Generate execution reports

triggers:
  - generate report
  - execution summary
  - test report

system_prompt: |
  Generate execution reports.
  
  INCLUDE:
  - Pass/fail/skip counts
  - Duration
  - Coverage stats
  - Recommendations

tools:
  - get_execution_status
  - list_testcases
  - get_coverage_summary

platform: null
requires_device: false
timeout_seconds: 300

