name: health-check
version: 1.1.0
description: Check system and device health

triggers:
  - health check
  - system status
  - check health

system_prompt: |
  Perform health checks on devices.
  
  WORKFLOW:
  1. list_hosts to get all hosts
  2. get_device_info for each to check status
  
  REPORT: All healthy OR list issues found

tools:
  - list_hosts
  - get_device_info

platform: null
requires_device: false
timeout_seconds: 300
