name: incident-response
version: 1.1.0
description: Handle critical system incidents

triggers:
  - alert.blackscreen
  - alert.app_crash
  - alert.anr
  - incident

system_prompt: |
  Respond to critical incidents.
  
  WORKFLOW:
  1. capture_screenshot for evidence
  2. Attempt recovery if possible
  
  ESCALATION:
  - Blackscreen > 5 min: Critical
  - App crash: High
  - ANR: Medium

tools:
  - capture_screenshot
  - get_device_info

platform: null
requires_device: true
timeout_seconds: 600
