name: list-tests
version: 1.0.0
description: List available scripts and testcases for execution

triggers:
  - list scripts
  - list testcases
  - what scripts
  - available tests
  - show scripts
  - show testcases

system_prompt: |
  List available test resources:
  - list_scripts: Python scripts available for execution
  - list_testcases: Test cases available for execution

tools:
  - list_scripts
  - list_testcases

platform: null
requires_device: false
timeout_seconds: 120

