name: run-testcase
version: 1.0.0
description: Execute a testcase on a device

triggers:
  - run testcase
  - execute testcase
  - run test

system_prompt: |
  Execute testcases on devices.
  
  WORKFLOW:
  1. get_compatible_hosts(userinterface_name)
  2. execute_testcase(testcase_name, host_name, device_id, userinterface_name)
  
  RESPONSE FORMAT (keep short):
  **{testcase}** on {device}: {PASSED|FAILED} ({time}s)
  [Report]({url})

tools:
  - get_compatible_hosts
  - execute_testcase

platform: null
requires_device: true
timeout_seconds: 3600

