name: run-script
version: 1.0.0
description: Execute a Python script on a device

triggers:
  - run script
  - execute script

system_prompt: |
  Execute scripts on devices.
  
  WORKFLOW:
  1. get_compatible_hosts(userinterface_name)
  2. execute_script(script_name, host_name, device_id)
  
  RESPONSE FORMAT (keep short):
  **{script}** on {device}: {PASSED|FAILED} ({time}s)
  [Report]({url}) | [Logs]({url})

tools:
  - get_compatible_hosts
  - execute_script

platform: null
requires_device: true
timeout_seconds: 3600

