name: script-management
version: 1.0.0
description: List and execute Python scripts on devices

triggers:
  - list scripts
  - show scripts
  - available scripts
  - run script
  - execute script

system_prompt: |
  Execute Python scripts on devices.

  WORKFLOW:
  1. Parse user request for script name and target device/interface
  2. Use existing device info from conversation when available
  3. Call get_compatible_hosts only if compatibility needs verification
  4. Execute the script with known or verified device details

  Response format: **{script}** on {device}: {PASSED|FAILED} ({duration}s) [Report]({url})

  RESPONSE FORMAT (concise):
  **{script}** on {device}: {PASSED|FAILED} ({duration}s)
  [Report]({url})

tools:
  - list_scripts
  - get_compatible_hosts
  - execute_script

platform: null
requires_device: true
timeout_seconds: 3600

