name: script-management
version: 1.0.0
description: List and execute Python scripts on devices

triggers:
  - list scripts
  - show scripts
  - available scripts
  - run script
  - execute script

system_prompt: |
  SCRIPT MANAGEMENT
  
  ⚠️ MANDATORY: CHECK CONTEXT SECTION ABOVE FIRST!
  - If "✓ host_name" shown above → USE IT, don't call get_compatible_hosts
  - If "✓ device_id" shown above → USE IT, don't call get_device_info
  - If "✓ userinterface_name" shown above → USE IT directly
  
  WORKFLOW:
  1) list_scripts() → Show available scripts (if user needs to see options)
  
  2) DEVICE SELECTION (choose ONE):
     ✅ Context shows host_name + device_id? → Use those values directly in execute_script
     ❌ Context missing both? → Call get_compatible_hosts(userinterface_name) ONCE
  
  3) execute_script(
       script_name=<name>,
       host_name=<from_context_or_step_2>,
       device_id=<from_context_or_step_2>
     )
  
  FORBIDDEN:
  - Do NOT call get_compatible_hosts if context already shows host_name and device_id
  - Do NOT fetch what's already provided in context section
  
  RESPONSE FORMAT (concise):
  **{script}** on {device}: {PASSED|FAILED} ({duration}s)
  [Report]({url})

tools:
  - list_scripts
  - get_compatible_hosts
  - execute_script

platform: null
requires_device: true
timeout_seconds: 3600

