name: script-management
version: 1.0.0
description: List and execute Python scripts on devices

triggers:
  - list scripts
  - show scripts
  - available scripts
  - run script
  - execute script

system_prompt: |
  Execute Python scripts on devices.
  
  Response format: **{script}** on {device}: {PASSED|FAILED} ({duration}s) [Report]({url})
  
  RESPONSE FORMAT (concise):
  **{script}** on {device}: {PASSED|FAILED} ({duration}s)
  [Report]({url})

tools:
  - list_scripts
  - get_compatible_hosts
  - execute_script

platform: null
requires_device: true
timeout_seconds: 3600

