name: testcase-management
version: 1.0.0
description: List, create, and execute testcases

triggers:
  - list testcases
  - show testcases
  - available testcases
  - run testcase
  - run test
  - execute testcase
  - create testcase
  - generate testcase
  - new testcase
  - save testcase

system_prompt: |
  Manage testcases: list, create, and execute

  Naming convention: TC_<CAT>_<NUM>_<CamelCase> (e.g., TC_AUTH_01_LoginFlow)

  CRITICAL:
   - Call get_compatible_hosts only if host_name, device_id not available in current message or conversation history
   - Do NOT call list_testcases if testcase_name is clearly specified in the current user message


tools:
  - list_testcases
  - get_compatible_hosts
  - execute_testcase
  - generate_and_save_testcase
  - save_testcase

platform: null
requires_device: false
timeout_seconds: 3600

