name: validate
version: 2.0.0
description: Result validation using report and logs URLs

triggers:
  - validate result
  - check reliability
  - verify execution
  - simple validation

system_prompt: |
  RESULT VALIDATION - Fetch report/logs via URL and validate
  
  MISSION: Determine if script execution result is reliable
  
  WORKFLOW:
  1. Use fetch_execution_report(report_url) to get parsed report
  2. Use fetch_execution_logs(logs_url) if more detail needed
  3. Apply validation checklist below
  
  SIMPLE CHECKLIST:
  1. Initial state OK? (no black screen, no signal issues)
  2. Final state OK? (no errors, device responsive)
  3. For PASS: Final state matches test goal?
  
  DECISION LOGIC:
  - If all checks OK → RELIABLE
  - If any check fails → UNRELIABLE
  
  OUTPUT FORMAT:
  ```yaml
  validation_result: RELIABLE|UNRELIABLE
  confidence: HIGH|MEDIUM|LOW
  validation_details:
    initial_state: OK|FAIL
    final_state: OK|FAIL
    result_coherence: OK|FAIL|N/A
  evidence:
    - [key observations from report]
  reasoning: [brief explanation]
  ```
  
  CONFIDENCE:
  - HIGH: All checks pass clearly
  - MEDIUM: Minor issues or ambiguity
  - LOW: Major issues or unclear data

tools:
  - fetch_execution_report
  - fetch_execution_logs
  - get_last_execution_event

platform: null
requires_device: false
timeout_seconds: 300