openapi: 3.0.0
info:
  title: HOST - Testcase Execution
  version: 1.0.0
  description: Host-side testcase execution
servers:
  - url: '{{host_url}}'
paths:
  /host/testcase/{testcase_id}/execute:
    post:
      summary: Execute Testcase
      tags: [Testcase]
      parameters:
        - name: testcase_id
          in: path
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Testcase execution started
          content:
            application/json:
              schema:
                type: object
  /host/testcase/execute:
    post:
      summary: Execute from Graph
      tags: [Testcase]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Execution started
          content:
            application/json:
              schema:
                type: object
  /host/testcase/execution/{execution_id}/status:
    get:
      summary: Get Execution Status
      tags: [Testcase]
      parameters:
        - name: execution_id
          in: path
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Execution status
          content:
            application/json:
              schema:
                type: object
  /host/testcase/{testcase_id}/history:
    get:
      summary: Get Execution History
      tags: [Testcase]
      parameters:
        - name: testcase_id
          in: path
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Execution history
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /host/testcase/execute-from-prompt:
    post:
      summary: Execute from Prompt (AI)
      tags: [Testcase]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: AI execution started
          content:
            application/json:
              schema:
                type: object
