openapi: 3.0.0
info:
  title: HOST - Testcase Execution
  version: 1.0.0
  description: Host-side testcase execution, monitoring, history tracking
servers:
  - url: '{{host_url}}'
paths:
  /testcase/{test_testcase_id}/execute:
    post:
      summary: Execute Testcase
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: test_testcase_id
        in: path
        required: true
        schema:
          type: string
  /testcase/execute:
    post:
      summary: Execute from Graph
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /testcase/execution/{test_execution_id}/status:
    get:
      summary: Get Execution Status
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: test_execution_id
        in: path
        required: true
        schema:
          type: string
  /testcase/{test_testcase_id}/history:
    get:
      summary: Get Execution History
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: test_testcase_id
        in: path
        required: true
        schema:
          type: string
  /testcase/execute-from-prompt:
    post:
      summary: Execute from Prompt (AI)
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
