openapi: 3.0.0
info:
  title: HOST - AI Exploration
  version: 1.0.0
  description: AI-powered UI exploration
servers:
  - url: '{{host_url}}'
paths:
  /host/ai-exploration/init:
    post:
      summary: Initialize Exploration
      tags: [AI-Exploration]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Exploration initialized
          content:
            application/json:
              schema:
                type: object
  /host/ai-exploration/start-exploration:
    post:
      summary: Start Exploration
      tags: [AI-Exploration]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Exploration started
          content:
            application/json:
              schema:
                type: object
  /host/ai-exploration/exploration-status/{exploration_id}:
    get:
      summary: Get Exploration Status
      tags: [AI-Exploration]
      parameters:
        - name: exploration_id
          in: path
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Exploration status
          content:
            application/json:
              schema:
                type: object
  /host/ai-exploration/continue-exploration:
    post:
      summary: Continue Exploration
      tags: [AI-Exploration]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Exploration continued
          content:
            application/json:
              schema:
                type: object
  /host/ai-exploration/start-validation:
    post:
      summary: Start Validation
      tags: [AI-Exploration]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Validation started
          content:
            application/json:
              schema:
                type: object
  /host/ai-exploration/finalize-structure:
    post:
      summary: Finalize Structure
      tags: [AI-Exploration]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Structure finalized
          content:
            application/json:
              schema:
                type: object
  /host/ai-exploration/cancel-exploration:
    post:
      summary: Cancel Exploration
      tags: [AI-Exploration]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Exploration cancelled
          content:
            application/json:
              schema:
                type: object
