openapi: 3.0.0
info:
  title: HOST - AI Exploration
  version: 1.0.0
  description: AI-powered UI exploration, navigation discovery, validation workflows
servers:
  - url: '{{host_url}}'
paths:
  /ai-exploration/init:
    post:
      summary: Initialize Exploration
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /ai-exploration/start-exploration:
    post:
      summary: Start Exploration
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /ai-exploration/exploration-status/{exploration_id}:
    get:
      summary: Get Exploration Status
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
    parameters:
      - name: exploration_id
        in: path
        required: true
        schema:
          type: string
  /ai-exploration/continue-exploration:
    post:
      summary: Continue Exploration
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /ai-exploration/start-validation:
    post:
      summary: Start Validation
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /ai-exploration/finalize-structure:
    post:
      summary: Finalize Structure
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
  /ai-exploration/cancel-exploration:
    post:
      summary: Cancel Exploration
      tags: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
