openapi: 3.0.0
info:
  title: SERVER - Core System & Health
  version: 1.0.0
  description: >-
    Core system endpoints for health checks, host registration, system metrics,
    and service monitoring.
servers:
  - url: '{{server_url}}'
    description: Development Server
    variables: {}
x-postman-variables:
  - key: server_url
    value: 'http://localhost:5109'
    description: Backend server URL
paths:
  /server/system/health:
    get:
      summary: Health Check
      description: Basic health check endpoint to verify server status and get system stats
      tags:
        - System
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  timestamp:
                    type: number
                  mode:
                    type: string
                  system_stats:
                    type: object
  /server/system/register:
    post:
      summary: Register Host
      description: Register a new host with the server for device management and monitoring
      tags:
        - System
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
          example: Bearer your_api_key_here
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - host_name
                - host_url
              properties:
                host_name:
                  type: string
                  description: Unique host name identifier
                host_url:
                  type: string
                  description: Host URL endpoint
                devices:
                  type: array
                  description: List of devices on this host (optional)
                  items:
                    type: object
                system_info:
                  type: object
                  description: System information (optional)
            example:
              host_name: "backend_host_1"
              host_url: "http://localhost:5109"
              devices:
                - device_id: "device1"
                  model: "Samsung S21"
              system_info:
                os: "Linux"
                version: "5.10"
      responses:
        '200':
          description: Host registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad request - missing required fields
  /server/system/ping:
    post:
      summary: Host Ping
      description: Hosts send periodic health ping to server with system stats and device metrics
      tags:
        - System
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
          example: Bearer your_api_key_here
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - host_name
              properties:
                host_name:
                  type: string
                  description: Host name identifier
                system_stats:
                  type: object
                  description: System-level statistics (CPU, memory, disk, etc.)
                  properties:
                    cpu_percent:
                      type: number
                    memory_percent:
                      type: number
                    disk_percent:
                      type: number
                per_device_metrics:
                  type: object
                  description: Per-device metrics (device_id as key)
                  additionalProperties:
                    type: object
            example:
              host_name: "backend_host_1"
              system_stats:
                cpu_percent: 45.5
                memory_percent: 62.3
                disk_percent: 78.1
              per_device_metrics:
                device1:
                  status: "active"
                  uptime: 3600
      responses:
        '200':
          description: Ping received successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad request - missing host_name
