openapi: 3.0.0
info:
  title: SERVER - Device Management
  version: 1.0.0
  description: >-
    Complete API testing for device management endpoints including CRUD
    operations for devices, controllers, and environment profiles.
servers:
  - url: '{{server_url}}'
paths:
  /devices/getAllDevices:
    get:
      summary: Get All Devices
      tags: []
      parameters:
        - name: team_id
          in: query
          description: Team ID to filter devices
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
      description: Retrieve all devices for a specific team
  /devices/createDevice:
    post:
      summary: Create Device
      tags: []
      parameters:
        - name: team_id
          in: query
          description: Team ID for device ownership
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
      description: Create a new device with complete configuration
  /devices/getDevice/{test_device_id}:
    get:
      summary: Get Device by ID
      tags: []
      parameters:
        - name: team_id
          in: query
          description: Team ID for authorization
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
      description: Retrieve a specific device by its ID
    parameters:
      - name: test_device_id
        in: path
        required: true
        schema:
          type: string
  /devices/updateDevice/{test_device_id}:
    put:
      summary: Update Device
      tags: []
      parameters:
        - name: team_id
          in: query
          description: Team ID for authorization
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
      description: Update an existing device configuration
    parameters:
      - name: test_device_id
        in: path
        required: true
        schema:
          type: string
  /devices/deleteDevice/{test_device_id}:
    delete:
      summary: Delete Device
      tags: []
      parameters:
        - name: team_id
          in: query
          description: Team ID for authorization
          schema:
            type: string
        - name: Authorization
          in: header
          schema:
            type: string
      responses: {}
      description: Delete a device from the system
    parameters:
      - name: test_device_id
        in: path
        required: true
        schema:
          type: string
