openapi: 3.0.0
info:
  title: SERVER - AI & Analysis
  version: 1.0.0
  description: AI-powered test generation and analysis
servers:
  - url: '{{server_url}}'
paths:
  /server/ai/analyzeCompatibility:
    post:
      summary: Analyze Compatibility
      tags: [AI]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Compatibility analysis result
          content:
            application/json:
              schema:
                type: object
  /server/ai/generatePlan:
    post:
      summary: Generate Plan
      tags: [AI]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Generated plan
          content:
            application/json:
              schema:
                type: object
  /server/ai/getStatus:
    post:
      summary: Get AI Status
      tags: [AI]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: AI status
          content:
            application/json:
              schema:
                type: object
  /server/ai/stopExecution:
    post:
      summary: Stop AI Execution
      tags: [AI]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Execution stopped
          content:
            application/json:
              schema:
                type: object
  /server/ai/analyzePrompt:
    post:
      summary: Analyze Prompt
      tags: [AI]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Prompt analysis
          content:
            application/json:
              schema:
                type: object
  /server/ai/resetCache:
    post:
      summary: Reset AI Cache
      tags: [AI]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cache reset
          content:
            application/json:
              schema:
                type: object
