openapi: 3.0.0
info:
  title: SERVER - Navigation Management
  version: 1.0.0
  description: Navigation tree and node management
servers:
  - url: '{{server_url}}'
paths:
  /server/navigation/goto:
    post:
      summary: Navigate to Node (Goto)
      tags: [Navigation]
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Navigation successful
          content:
            application/json:
              schema:
                type: object
  /server/navigation/config/createEmpty/{ui_name}:
    post:
      summary: Create Empty Navigation Config
      tags: [Navigation]
      parameters:
        - name: ui_name
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Config created
          content:
            application/json:
              schema:
                type: object
  /server/navigation-trees/getTree/{navigation_id}:
    get:
      summary: Get Navigation Tree
      tags: [Navigation]
      parameters:
        - name: navigation_id
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Navigation tree details
          content:
            application/json:
              schema:
                type: object
  /server/navigation-trees/getAllTrees:
    get:
      summary: Get All Navigation Trees
      tags: [Navigation]
      parameters:
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of navigation trees
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /server/navigation-trees/deleteTree/{navigation_id}:
    delete:
      summary: Delete Navigation Tree
      tags: [Navigation]
      parameters:
        - name: navigation_id
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tree deleted
          content:
            application/json:
              schema:
                type: object
