openapi: 3.0.0
info:
  title: SERVER - Campaign Management
  version: 1.0.0
  description: Campaign CRUD operations
servers:
  - url: '{{server_url}}'
paths:
  /server/campaigns/getAllCampaigns:
    get:
      summary: Get All Campaigns
      tags: [Campaigns]
      parameters:
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of campaigns
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /server/campaigns/createCampaign:
    post:
      summary: Create Campaign
      tags: [Campaigns]
      parameters:
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Campaign created
          content:
            application/json:
              schema:
                type: object
  /server/campaigns/getCampaign/{campaign_id}:
    get:
      summary: Get Campaign by ID
      tags: [Campaigns]
      parameters:
        - name: campaign_id
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Campaign details
          content:
            application/json:
              schema:
                type: object
  /server/campaigns/updateCampaign/{campaign_id}:
    put:
      summary: Update Campaign
      tags: [Campaigns]
      parameters:
        - name: campaign_id
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Campaign updated
          content:
            application/json:
              schema:
                type: object
  /server/campaigns/deleteCampaign/{campaign_id}:
    delete:
      summary: Delete Campaign
      tags: [Campaigns]
      parameters:
        - name: campaign_id
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Campaign deleted
          content:
            application/json:
              schema:
                type: object
