openapi: 3.0.0
info:
  title: SERVER - Device Management
  version: 1.0.0
  description: Device CRUD operations
servers:
  - url: '{{server_url}}'
paths:
  /server/devices/getAllDevices:
    get:
      summary: Get All Devices
      tags: [Devices]
      parameters:
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          example: Bearer {{api_key}}
      responses:
        '200':
          description: List of devices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /server/devices/createDevice:
    post:
      summary: Create Device
      tags: [Devices]
      parameters:
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device created
          content:
            application/json:
              schema:
                type: object
  /server/devices/getDevice/{device_id}:
    get:
      summary: Get Device by ID
      tags: [Devices]
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device details
          content:
            application/json:
              schema:
                type: object
  /server/devices/updateDevice/{device_id}:
    put:
      summary: Update Device
      tags: [Devices]
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device updated
          content:
            application/json:
              schema:
                type: object
  /server/devices/deleteDevice/{device_id}:
    delete:
      summary: Delete Device
      tags: [Devices]
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device deleted
          content:
            application/json:
              schema:
                type: object
