openapi: 3.0.0
info:
  title: SERVER - Device Management
  version: 1.0.0
  description: Device CRUD operations
servers:
  - url: '{{server_url}}'
    description: Development Server
    variables: {}
x-postman-variables:
  - key: server_url
    value: 'http://localhost:5109'
    description: Backend server URL
paths:
  /server/devices/getAllDevices:
    get:
      summary: Get All Devices
      tags: [Devices]
      parameters:
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          example: Bearer your_api_key_here
      responses:
        '200':
          description: List of devices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /server/devices/createDevice:
    post:
      summary: Create Device
      description: Create a new device in the device_flags table (auto-registered from hosts)
      tags: [Devices]
      parameters:
        - name: team_id
          in: query
          required: true
          schema:
            type: string
          description: Team identifier
          example: "team_123"
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
          example: Bearer your_api_key_here
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - model
              properties:
                name:
                  type: string
                  description: Device name
                description:
                  type: string
                  description: Device description (optional)
                model:
                  type: string
                  description: Device model name
                controller_configs:
                  type: object
                  description: Controller configuration JSON (optional)
            example:
              name: "Samsung_S21_Device1"
              description: "Test device for QA"
              model: "Samsung S21"
              controller_configs:
                av: "av_controller_1"
                power: "power_controller_1"
      responses:
        '201':
          description: Device created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  device:
                    type: object
        '400':
          description: Bad request - missing required fields
        '500':
          description: Internal error creating device
  /server/devices/getDevice/{device_id}:
    get:
      summary: Get Device by ID
      description: Retrieve detailed information about a specific device
      tags: [Devices]
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
          description: Device identifier
          example: "device_001"
        - name: host_name
          in: query
          required: false
          schema:
            type: string
          description: Host name where device is located (optional)
          example: "backend_host_1"
        - name: team_id
          in: query
          required: true
          schema:
            type: string
          description: Team identifier
          example: "team_123"
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
          example: Bearer your_api_key_here
      responses:
        '200':
          description: Device details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  model:
                    type: string
                  description:
                    type: string
                  controller_configs:
                    type: object
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: Device not found
        '500':
          description: Internal error retrieving device
  /server/devices/updateDevice/{device_id}:
    put:
      summary: Update Device
      description: Update an existing device's information
      tags: [Devices]
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
          description: Device identifier
          example: "device_001"
        - name: team_id
          in: query
          required: true
          schema:
            type: string
          description: Team identifier
          example: "team_123"
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
          example: Bearer your_api_key_here
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Device name
                  example: "Samsung_S21_Device1"
                description:
                  type: string
                  description: Device description
                  example: "Updated description"
                model:
                  type: string
                  description: Device model name
                  example: "Samsung S21"
                controller_configs:
                  type: object
                  description: Controller configuration JSON
                  example: {"av": "av_controller_1", "power": "power_controller_1"}
      responses:
        '200':
          description: Device updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  device:
                    type: object
        '400':
          description: Bad request
        '404':
          description: Device not found
        '500':
          description: Internal error updating device
  /server/devices/deleteDevice/{device_id}:
    delete:
      summary: Delete Device
      tags: [Devices]
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device deleted
          content:
            application/json:
              schema:
                type: object
