openapi: 3.0.0
info:
  title: SERVER - Testcase Management
  version: 1.0.0
  description: Test case CRUD operations
servers:
  - url: '{{server_url}}'
paths:
  /server/testcase/list:
    get:
      summary: List All Testcases
      tags: [Testcases]
      parameters:
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: include_inactive
          in: query
          schema:
            type: boolean
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of testcases
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /server/testcase/save:
    post:
      summary: Create or Update Testcase
      description: Create a new testcase or update an existing one. If testcase_id is provided, updates existing testcase; otherwise creates new one.
      tags: [Testcases]
      parameters:
        - name: team_id
          in: query
          required: true
          schema:
            type: string
          description: Team identifier
          example: "{{team_id}}"
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
          example: Bearer {{api_key}}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - testcase_name
                - graph_json
              properties:
                testcase_id:
                  type: string
                  description: Testcase ID (required for updates, omit for new testcase)
                  example: "{{testcase_id}}"
                testcase_name:
                  type: string
                  description: Testcase name
                  example: "{{testcase_name}}"
                graph_json:
                  type: object
                  description: Graph JSON defining the testcase workflow (nodes and edges)
                  example: {"nodes": [], "edges": []}
                description:
                  type: string
                  description: Testcase description (optional)
                  example: "Validation testcase for login flow"
                userinterface_name:
                  type: string
                  description: User interface name (optional)
                  example: "{{userinterface_name}}"
                folder:
                  type: string
                  description: Folder name to organize testcase (optional)
                  example: "Regression Tests"
                tags:
                  type: array
                  description: List of tag names (optional)
                  items:
                    type: string
                  example: ["login", "regression"]
                overwrite:
                  type: boolean
                  description: Allow overwriting existing testcase with same name (optional, default false)
                  example: false
                created_by:
                  type: string
                  description: User ID of creator (optional)
                  example: "{{user_id}}"
                creation_method:
                  type: string
                  description: Creation method (optional, default 'visual')
                  enum: [visual, ai, import]
                  example: "visual"
                ai_prompt:
                  type: string
                  description: AI prompt used if created with AI (optional)
                  example: "Create a login validation test"
                ai_analysis:
                  type: object
                  description: AI analysis result if created with AI (optional)
                available_nodes:
                  type: array
                  description: Available nodes from AI generation (optional)
                  items:
                    type: object
      responses:
        '200':
          description: Testcase created or updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  testcase:
                    type: object
                  testcase_id:
                    type: string
                  testcase_name:
                    type: string
                  action:
                    type: string
                    enum: [created, updated]
        '400':
          description: Bad request - missing required fields or validation failed
        '404':
          description: Testcase not found (for updates)
        '409':
          description: Duplicate testcase name (when overwrite is false)
        '500':
          description: Internal error saving testcase
  /server/testcase/{testcase_id}:
    get:
      summary: Get Testcase by ID
      tags: [Testcases]
      parameters:
        - name: testcase_id
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Testcase details
          content:
            application/json:
              schema:
                type: object
    delete:
      summary: Delete Testcase
      tags: [Testcases]
      parameters:
        - name: testcase_id
          in: path
          required: true
          schema:
            type: string
        - name: team_id
          in: query
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Testcase deleted
          content:
            application/json:
              schema:
                type: object
