export const androidTvRemoteConfig = {
  remote_info: {
    name: 'Android TV',
    type: 'android_tv' as const,
    image_url: '/androidtv_remote.png',
    default_scale: 1,
    min_scale: 0.3,
    max_scale: 1.0,
    button_scale_factor: 4,
    global_offset: { x: 0, y: 0 },
    text_style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '2px 2px 4px rgba(0,0,0,0.9)',
    },
  },
  panel_layout: {
    collapsed: {
      width: '160px',
      height: '300px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '240px',
      height: '600px',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: true,
    header: {

      fontSize: '0.875rem',
      fontWeight: 'bold',
      iconSize: 'small',
      padding: '8px',
      backgroundColor: '#1E1E1E',
      borderColor: '#333',
      textColor: '#ffffff',
    },
  },
  remote_layout: {
    collapsed: {
      width: '250px',
      height: '150px',
      scale: 1,
      padding: '25px',
    },
    expanded: {
      width: '400px',
      height: '300px',
      scale: 1.0,
      padding: '50px',
    },
    background_image: {
      url: '/androidtv_remote.png',
      width: 400,
      height: 300,
    },

  },
  button_layout: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 122, y: 76 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 235, y: 280 },
      size: { width: 20, height: 16 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 108, y: 404 },
      size: { width: 16, height: 20 },
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'SELECT',
      label: 'OK',
      position: { x: 179, y: 345 },
      size: { width: 50, height: 50 },
      shape: 'circle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 384, y: 404 },
      size: { width: 16, height: 20 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 235, y: 546 },
      size: { width: 20, height: 16 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '←',
      position: { x: 110, y: 644 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 235, y: 644 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'HOME',
    },
    menu: {
      key: 'MENU',
      label: '',
      position: { x: 358, y: 644 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'MENU',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 110, y: 765 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'REWIND',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '',
      position: { x: 235, y: 766 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'PLAY_PAUSE',
    },
    fast_forward: {
      key: 'FAST_FORWARD',
      label: '',
      position: { x: 358, y: 766 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'FAST_FORWARD',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 235, y: 886 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 235, y: 1010 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'VOLUME_MUTE',
      label: '',
      position: { x: 236, y: 1134 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'MUTE',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: 'CH+',
      position: { x: 364, y: 886 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'CHANNEL_UP',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: 'CH-',
      position: { x: 364, y: 1010 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'CHANNEL_DOWN',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 132, y: 81 },
      size: { width: 21, height: 21 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 261, y: 300 },
      size: { width: 26, height: 20 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 103, y: 446 },
      size: { width: 20, height: 26 },
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'SELECT',
      label: 'OK',
      position: { x: 195, y: 384 },
      size: { width: 60, height: 60 },
      shape: 'circle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 442, y: 446 },
      size: { width: 16, height: 28 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 261, y: 626 },
      size: { width: 28, height: 16 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 122, y: 716 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 261, y: 716 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'HOME',
    },
    menu: {
      key: 'MENU',
      label: '',
      position: { x: 398, y: 716 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'MENU',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 122, y: 852 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'REWIND',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '',
      position: { x: 261, y: 852 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'PLAY_PAUSE',
    },
    fast_forward: {
      key: 'FAST_FORWARD',
      label: '',
      position: { x: 398, y: 852 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'FAST_FORWARD',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 261, y: 989 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 261, y: 1120 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'VOLUME_MUTE',
      label: '',
      position: { x: 263, y: 1260 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'MUTE',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: 'CH+',
      position: { x: 398, y: 989 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'CHANNEL_UP',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: 'CH-',
      position: { x: 398, y: 1120 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'CHANNEL_DOWN',
    },
  },
} as const;

export type AndroidTvRemoteConfig = typeof androidTvRemoteConfig;
