export const appleTvRemoteConfig = {
  remote_info: {
    name: 'Apple TV',
    type: 'ir_remote' as const,
    image_url: '/appletv_remote.png',
    default_scale: 1,
    min_scale: 0.3,
    max_scale: 1.0,
    button_scale_factor: 4,
    global_offset: { x: 0, y: 0 },
    text_style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '2px 2px 4px rgba(0,0,0,0.9)',
    },
  },
  panel_layout: {
    collapsed: {
      width: '160px',
      height: '300px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '240px',
      height: '600px',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: true,
    header: {
      height: '40px',
      fontSize: '0.875rem',
      fontWeight: 'bold',
      iconSize: 'small',
      padding: '8px',
      backgroundColor: '#1E1E1E',
      borderColor: '#333',
      textColor: '#ffffff',
    },
  },
  remote_layout: {
    collapsed: {
      width: '120px',
      height: '240px',
      scale: 0.6,
      padding: '10px',
    },
    expanded: {
      width: '200px',
      height: '500px',
      scale: 1.0,
      padding: '25px',
    },
    background_image: {
      url: '/appletv_remote.png',
      width: 200,
      height: 500,
    },
    global_offset: {
      x: 0,
      y: 0,
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 100, y: 50 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    nav_up: {
      key: 'UP',
      label: '',
      position: { x: 100, y: 150 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '',
      position: { x: 50, y: 200 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'OK',
      label: '',
      position: { x: 100, y: 200 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '',
      position: { x: 150, y: 200 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '',
      position: { x: 100, y: 250 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 50, y: 300 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 100, y: 100 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'HOME',
    },
    menu: {
      key: 'MENU',
      label: '',
      position: { x: 150, y: 300 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'MENU',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 50, y: 350 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 50, y: 400 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'MUTE',
      label: '',
      position: { x: 100, y: 375 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'MUTE',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 50, y: 450 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'REWIND',
    },
    play: {
      key: 'PLAY',
      label: '',
      position: { x: 100, y: 450 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'PLAY',
    },
    pause: {
      key: 'PAUSE',
      label: '',
      position: { x: 100, y: 450 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'PAUSE',
    },
    fast_forward: {
      key: 'FORWARD',
      label: '',
      position: { x: 150, y: 450 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'FORWARD',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 100, y: 50 },
      size: { width: 35, height: 35 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    nav_up: {
      key: 'UP',
      label: '',
      position: { x: 100, y: 150 },
      size: { width: 30, height: 30 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '',
      position: { x: 50, y: 200 },
      size: { width: 30, height: 30 },
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'OK',
      label: '',
      position: { x: 100, y: 200 },
      size: { width: 35, height: 35 },
      shape: 'circle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '',
      position: { x: 150, y: 200 },
      size: { width: 30, height: 30 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '',
      position: { x: 100, y: 250 },
      size: { width: 30, height: 30 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 50, y: 300 },
      size: { width: 30, height: 30 },
      shape: 'rectangle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 100, y: 100 },
      size: { width: 35, height: 35 },
      shape: 'circle' as const,
      comment: 'HOME',
    },
    menu: {
      key: 'MENU',
      label: '',
      position: { x: 150, y: 300 },
      size: { width: 30, height: 30 },
      shape: 'rectangle' as const,
      comment: 'MENU',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 50, y: 350 },
      size: { width: 30, height: 30 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 50, y: 400 },
      size: { width: 30, height: 30 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'MUTE',
      label: '',
      position: { x: 100, y: 375 },
      size: { width: 30, height: 30 },
      shape: 'rectangle' as const,
      comment: 'MUTE',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 50, y: 450 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'REWIND',
    },
    play: {
      key: 'PLAY',
      label: '',
      position: { x: 100, y: 450 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'PLAY',
    },
    pause: {
      key: 'PAUSE',
      label: '',
      position: { x: 100, y: 450 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'PAUSE',
    },
    fast_forward: {
      key: 'FORWARD',
      label: '',
      position: { x: 150, y: 450 },
      size: { width: 25, height: 25 },
      shape: 'rectangle' as const,
      comment: 'FORWARD',
    },
  },
};
