export const eosRemoteConfig = {
  remote_info: {
    name: 'EOS',
    type: 'ir_remote' as const,
    image_url: '/eos_remote.png',
    default_scale: 1,
    min_scale: 0.3,
    max_scale: 1.0,
    button_scale_factor: 4,
    global_offset: { x: 0, y: 0 },
    text_style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '2px 2px 4px rgba(0,0,0,0.9)',
    },
  },
  panel_layout: {
    collapsed: {
      width: '160px',
      height: '300px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '240px',
      height: '600px',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: true,
    header: {
      height: '40px',
      fontSize: '0.875rem',
      fontWeight: 'bold',
      iconSize: 'small',
      padding: '8px',
      backgroundColor: '#1E1E1E',
      borderColor: '#333',
      textColor: '#ffffff',
    },
  },
  remote_layout: {
    collapsed: {
      width: '120px',
      height: '240px',
      scale: 0.6,
      padding: '10px',
    },
    expanded: {
      width: '200px',
      height: '500px',
      scale: 1.0,
      padding: '25px',
    },
    background_image: {
      url: '/eos_remote.png',
      width: 200,
      height: 500,
    },
    global_offset: {
      x: 0,
      y: 0,
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 340, y: 28 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 228, y: 350 },
      size: { width: 26, height: 20 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 140, y: 430 },
      size: { width: 20, height: 26 },
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 228, y: 434 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 336, y: 430 },
      size: { width: 20, height: 26 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 228, y: 542 },
      size: { width: 26, height: 20 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 129, y: 618 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 230, y: 218 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'HOME',
    },
    menu: {
      key: 'MENU',
      label: '',
      position: { x: 360, y: 616 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'MENU',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: '',
      position: { x: 350, y: 734 },
      size: { width: 20, height: 22 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_UP',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: '',
      position: { x: 350, y: 830 },
      size: { width: 20, height: 22 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_DOWN',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 138, y: 734 },
      size: { width: 20, height: 22 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 138, y: 830 },
      size: { width: 20, height: 22 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'MUTE',
      label: '',
      position: { x: 114, y: 1324 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'MUTE',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 138, y: 945 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'REWIND',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '',
      position: { x: 243, y: 945 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'PLAY_PAUSE',
    },
    rec: {
      key: 'RECORD',
      label: '',
      position: { x: 243, y: 836 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'RECORD',
    },
    fast_forward: {
      key: 'FORWARD',
      label: '',
      position: { x: 350, y: 945 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'FORWARD',
    },
    tv_guide: {
      key: 'TVGUIDE',
      label: '',
      position: { x: 128, y: 282 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'TVGUIDE',
    },
    number_1: {
      key: 'KEY_1',
      label: '',
      position: { x: 114, y: 1058 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_1',
    },
    number_2: {
      key: 'KEY_2',
      label: '',
      position: { x: 230, y: 1058 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_2',
    },
    number_3: {
      key: 'KEY_3',
      label: '',
      position: { x: 346, y: 1058 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_3',
    },
    number_4: {
      key: 'KEY_4',
      label: '',
      position: { x: 114, y: 1148 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_4',
    },
    number_5: {
      key: 'KEY_5',
      label: '',
      position: { x: 230, y: 1148 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_5',
    },
    number_6: {
      key: 'KEY_6',
      label: '',
      position: { x: 346, y: 1148 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_6',
    },
    number_7: {
      key: 'KEY_7',
      label: '',
      position: { x: 114, y: 1236 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_7',
    },
    number_8: {
      key: 'KEY_8',
      label: '',
      position: { x: 230, y: 1236 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_8',
    },
    number_9: {
      key: 'KEY_9',
      label: '',
      position: { x: 346, y: 1236 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_9',
    },
    number_0: {
      key: 'KEY_0',
      label: '',
      position: { x: 230, y: 1324 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_0',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 380, y: 32 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 258, y: 380 },
      size: { width: 28, height: 24 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 156, y: 484 },
      size: { width: 24, height: 28 },
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 258, y: 484 },
      size: { width: 28, height: 28 },
      shape: 'circle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 376, y: 484 },
      size: { width: 24, height: 28 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 258, y: 602 },
      size: { width: 28, height: 24 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 146, y: 690 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 256, y: 240 },
      size: { width: 28, height: 28 },
      shape: 'circle' as const,
      comment: 'HOME',
    },
    menu: {
      key: 'MENU',
      label: '',
      position: { x: 402, y: 688 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'MENU',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: '',
      position: { x: 394, y: 816 },
      size: { width: 20, height: 26 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_UP',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: '',
      position: { x: 394, y: 922 },
      size: { width: 20, height: 26 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_DOWN',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 158, y: 816 },
      size: { width: 20, height: 26 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 158, y: 922 },
      size: { width: 20, height: 26 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'MUTE',
      label: '',
      position: { x: 146, y: 1484 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'MUTE',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 158, y: 1055 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'REWIND',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '',
      position: { x: 273, y: 1055 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'PLAY_PAUSE',
    },
    rec: {
      key: 'RECORD',
      label: '',
      position: { x: 273, y: 934 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'RECORD',
    },
    fast_forward: {
      key: 'FORWARD',
      label: '',
      position: { x: 390, y: 1055 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'FORWARD',
    },
    tv_guide: {
      key: 'TVGUIDE',
      label: '',
      position: { x: 148, y: 320 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'TVGUIDE',
    },
    number_1: {
      key: 'KEY_1',
      label: '',
      position: { x: 146, y: 1188 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_1',
    },
    number_2: {
      key: 'KEY_2',
      label: '',
      position: { x: 270, y: 1188 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_2',
    },
    number_3: {
      key: 'KEY_3',
      label: '',
      position: { x: 394, y: 1188 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_3',
    },
    number_4: {
      key: 'KEY_4',
      label: '',
      position: { x: 146, y: 1288 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_4',
    },
    number_5: {
      key: 'KEY_5',
      label: '',
      position: { x: 270, y: 1288 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_5',
    },
    number_6: {
      key: 'KEY_6',
      label: '',
      position: { x: 394, y: 1288 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_6',
    },
    number_7: {
      key: 'KEY_7',
      label: '',
      position: { x: 146, y: 1388 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_7',
    },
    number_8: {
      key: 'KEY_8',
      label: '',
      position: { x: 270, y: 1388 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_8',
    },
    number_9: {
      key: 'KEY_9',
      label: '',
      position: { x: 394, y: 1388 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_9',
    },
    number_0: {
      key: 'KEY_0',
      label: '',
      position: { x: 270, y: 1484 },
      size: { width: 28, height: 20 },
      shape: 'rectangle' as const,
      comment: 'KEY_0',
    },
  },
};
