import { InfraredRemoteConfig, INFRARED_REMOTE_DEFAULTS } from './infraredRemoteBase';

export const eosRemoteConfig: InfraredRemoteConfig = {
  remote_info: {
    ...INFRARED_REMOTE_DEFAULTS.remote_info,
    name: 'EOS Remote',
    image_url: '/eos_remote.png',
  },
  panel_layout: {
    ...INFRARED_REMOTE_DEFAULTS.panel_layout,
  },
  remote_layout: {
    ...INFRARED_REMOTE_DEFAULTS.remote_layout,
    background_image: {
      url: '/eos_remote.png',
      width: 200,
      height: 500,
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 100, y: 30 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    source: {
      key: 'SOURCE',
      label: 'SRC',
      position: { x: 70, y: 60 },
      size: { width: 15, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Source/Input button',
    },
    info: {
      key: 'INFO',
      label: 'INFO',
      position: { x: 130, y: 60 },
      size: { width: 15, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Info button',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 100, y: 100 },
      size: { width: 15, height: 12 },
      shape: 'rectangle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 70, y: 130 },
      size: { width: 12, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 100, y: 130 },
      size: { width: 25, height: 25 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 130, y: 130 },
      size: { width: 12, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 100, y: 160 },
      size: { width: 15, height: 12 },
      shape: 'rectangle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '←',
      position: { x: 70, y: 190 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 100, y: 190 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 130, y: 190 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: 'V+',
      position: { x: 70, y: 220 },
      size: { width: 15, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Volume up button',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: 'CH+',
      position: { x: 130, y: 220 },
      size: { width: 15, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Channel up button',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: 'V-',
      position: { x: 70, y: 250 },
      size: { width: 15, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Volume down button',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: 'CH-',
      position: { x: 130, y: 250 },
      size: { width: 15, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Channel down button',
    },
    mute: {
      key: 'MUTE',
      label: '🔇',
      position: { x: 100, y: 280 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Mute button',
    },
    rewind: {
      key: 'REWIND',
      label: '<<',
      position: { x: 70, y: 310 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Rewind button',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '⏯',
      position: { x: 100, y: 310 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Play/pause button',
    },
    fast_forward: {
      key: 'FAST_FORWARD',
      label: '>>',
      position: { x: 130, y: 310 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Fast forward button',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 130, y: 39 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    source: {
      key: 'SOURCE',
      label: 'SRC',
      position: { x: 91, y: 78 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Source/Input button',
    },
    info: {
      key: 'INFO',
      label: 'INFO',
      position: { x: 169, y: 78 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Info button',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 130, y: 130 },
      size: { width: 20, height: 16 },
      shape: 'rectangle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 91, y: 169 },
      size: { width: 16, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 130, y: 169 },
      size: { width: 32, height: 32 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 169, y: 169 },
      size: { width: 16, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 130, y: 208 },
      size: { width: 20, height: 16 },
      shape: 'rectangle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '←',
      position: { x: 91, y: 247 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 130, y: 247 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 169, y: 247 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: 'V+',
      position: { x: 91, y: 286 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Volume up button',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: 'CH+',
      position: { x: 169, y: 286 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Channel up button',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: 'V-',
      position: { x: 91, y: 325 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Volume down button',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: 'CH-',
      position: { x: 169, y: 325 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Channel down button',
    },
    mute: {
      key: 'MUTE',
      label: '🔇',
      position: { x: 130, y: 364 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Mute button',
    },
    rewind: {
      key: 'REWIND',
      label: '<<',
      position: { x: 91, y: 403 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Rewind button',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '⏯',
      position: { x: 130, y: 403 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Play/pause button',
    },
    fast_forward: {
      key: 'FAST_FORWARD',
      label: '>>',
      position: { x: 169, y: 403 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Fast forward button',
    },
  },
} as const;

export type EosRemoteConfig = typeof eosRemoteConfig;
