export const eosRemoteConfig = {
  remote_info: {
    name: 'EOS Remote',
    type: 'ir_remote' as const,
    image_url: '/eos_remote.png',
    default_scale: 1,
    min_scale: 0.3,
    max_scale: 1.0,
    button_scale_factor: 4,
    global_offset: { x: 0, y: 0 },
    text_style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '2px 2px 4px rgba(0,0,0,0.9)',
    },
  },
  panel_layout: {
    collapsed: {
      width: '160px',
      height: '300px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '240px',
      height: '600px',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: true,
    header: {
      height: '40px',
      fontSize: '0.875rem',
      fontWeight: 'bold',
      iconSize: 'small',
      padding: '8px',
      backgroundColor: '#1E1E1E',
      borderColor: '#333',
      textColor: '#ffffff',
    },
  },
  remote_layout: {
    collapsed: {
      width: '120px',
      height: '240px',
      scale: 0.6,
      padding: '10px',
    },
    expanded: {
      width: '200px',
      height: '500px',
      scale: 1.0,
      padding: '25px',
    },
    background_image: {
      url: '/eos_remote.png',
      width: 200,
      height: 500,
    },
    global_offset: {
      x: 0,
      y: 0,
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 336, y: 104 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'Power button - red circle top right',
    },
    source: {
      key: 'SOURCE',
      label: 'SRC',
      position: { x: 144, y: 144 },
      size: { width: 25, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Source button - SRC label top left',
    },
    info: {
      key: 'INFO',
      label: 'INFO',
      position: { x: 310, y: 144 },
      size: { width: 30, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Info button - INFO label top right',
    },
    nav_up: {
      key: 'UP',
      label: '',
      position: { x: 200, y: 540 },
      size: { width: 20, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Navigation up - top of circular pad',
    },
    nav_left: {
      key: 'LEFT',
      label: '',
      position: { x: 120, y: 600 },
      size: { width: 15, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation left - left of circular pad',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 200, y: 600 },
      size: { width: 40, height: 40 },
      shape: 'circle' as const,
      comment: 'Navigation center - OK button in middle',
    },
    nav_right: {
      key: 'RIGHT',
      label: '',
      position: { x: 280, y: 600 },
      size: { width: 15, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation right - right of circular pad',
    },
    nav_down: {
      key: 'DOWN',
      label: '',
      position: { x: 200, y: 660 },
      size: { width: 20, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Navigation down - bottom of circular pad',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 120, y: 780 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'Back button - curved arrow',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 200, y: 400 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Home button - house icon',
    },
    menu: {
      key: 'MENU',
      label: '',
      position: { x: 320, y: 780 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'Menu button - three dots',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: 'V+',
      position: { x: 144, y: 216 },
      size: { width: 25, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Volume up - V+ label left side',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: 'CH+',
      position: { x: 144, y: 250 },
      size: { width: 25, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Channel up - CH+ label left side',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: 'V-',
      position: { x: 144, y: 284 },
      size: { width: 25, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Volume down - V- label left side',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: 'CH-',
      position: { x: 144, y: 318 },
      size: { width: 25, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Channel down - CH- label left side',
    },
    mute: {
      key: 'MUTE',
      label: '',
      position: { x: 120, y: 1200 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'Mute button - speaker icon bottom left',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 120, y: 1080 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'Rewind button - left arrow',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '',
      position: { x: 200, y: 1080 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Play/pause - red circle button',
    },
    fast_forward: {
      key: 'FAST_FORWARD',
      label: '',
      position: { x: 280, y: 1080 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'Fast forward - right arrow',
    },
    voice: {
      key: 'VOICE',
      label: '',
      position: { x: 200, y: 900 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'Voice button - microphone icon',
    },
    number_1: {
      key: '1',
      label: '1',
      position: { x: 120, y: 1280 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Number 1',
    },
    number_2: {
      key: '2',
      label: '2',
      position: { x: 200, y: 1280 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Number 2',
    },
    number_3: {
      key: '3',
      label: '3',
      position: { x: 280, y: 1280 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Number 3',
    },
    number_4: {
      key: '4',
      label: '4',
      position: { x: 120, y: 1340 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Number 4',
    },
    number_5: {
      key: '5',
      label: '5',
      position: { x: 200, y: 1340 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Number 5',
    },
    number_6: {
      key: '6',
      label: '6',
      position: { x: 280, y: 1340 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Number 6',
    },
    number_7: {
      key: '7',
      label: '7',
      position: { x: 120, y: 1400 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Number 7',
    },
    number_8: {
      key: '8',
      label: '8',
      position: { x: 200, y: 1400 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Number 8',
    },
    number_9: {
      key: '9',
      label: '9',
      position: { x: 280, y: 1400 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Number 9',
    },
    number_0: {
      key: '0',
      label: '0',
      position: { x: 200, y: 1460 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Number 0',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 130, y: 39 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    source: {
      key: 'SOURCE',
      label: 'SRC',
      position: { x: 91, y: 78 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Source/Input button',
    },
    info: {
      key: 'INFO',
      label: 'INFO',
      position: { x: 169, y: 78 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Info button',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 130, y: 130 },
      size: { width: 20, height: 16 },
      shape: 'rectangle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 91, y: 169 },
      size: { width: 16, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 130, y: 169 },
      size: { width: 32, height: 32 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 169, y: 169 },
      size: { width: 16, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 130, y: 208 },
      size: { width: 20, height: 16 },
      shape: 'rectangle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '←',
      position: { x: 91, y: 247 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 130, y: 247 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 169, y: 247 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: 'V+',
      position: { x: 91, y: 286 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Volume up button',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: 'CH+',
      position: { x: 169, y: 286 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Channel up button',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: 'V-',
      position: { x: 91, y: 325 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Volume down button',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: 'CH-',
      position: { x: 169, y: 325 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Channel down button',
    },
    mute: {
      key: 'MUTE',
      label: '🔇',
      position: { x: 130, y: 364 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Mute button',
    },
    rewind: {
      key: 'REWIND',
      label: '<<',
      position: { x: 91, y: 403 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Rewind button',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '⏯',
      position: { x: 130, y: 403 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Play/pause button',
    },
    fast_forward: {
      key: 'FAST_FORWARD',
      label: '>>',
      position: { x: 169, y: 403 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Fast forward button',
    },
  },
};
