export const firetvRemoteConfig = {
  remote_info: {
    name: 'Fire TV',
    type: 'ir_remote' as const,
    image_url: '/firetv_remote.png',
    default_scale: 1,
    min_scale: 0.3,
    max_scale: 1.0,
    button_scale_factor: 1.5,
    global_offset: { x: 0, y: 0 },
    text_style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '2px 2px 4px rgba(0,0,0,0.9)',
    },
  },
  panel_layout: {
    collapsed: {
      width: '160px',
      height: '300px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '240px',
      height: '600px',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: true,
    header: {
      height: '48px',
      fontSize: '0.875rem',
      fontWeight: 'bold',
      iconSize: 'small',
      padding: '8px',
      backgroundColor: '#1E1E1E',
      borderColor: '#333',
      textColor: '#ffffff',
    },
  },
  remote_layout: {
    collapsed: {
      width: '250px',
      height: '150px',
      scale: 1,
      padding: '25px',
    },
    expanded: {
      width: '400px',
      height: '300px',
      scale: 1.0,
      padding: '50px',
    },
    background_image: {
      url: '/firetv_remote.png',
      width: 400,
      height: 300,
    },
    global_offset: {
      x: 0,
      y: 0,
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 110, y: 70 },
      size: { width: 14, height: 14 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 210, y: 256 },
      size: { width: 18, height: 14 },
      shape: 'rectangle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 100, y: 360 },
      size: { width: 14, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'SELECT',
      label: 'OK',
      position: { x: 160, y: 310 },
      size: { width: 45, height: 45 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 340, y: 360 },
      size: { width: 14, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 210, y: 490 },
      size: { width: 18, height: 14 },
      shape: 'rectangle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '←',
      position: { x: 99, y: 574 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 210, y: 574 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 318, y: 574 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 144, y: 93 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 276, y: 326 },
      size: { width: 26, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 116, y: 470 },
      size: { width: 20, height: 26 },
      shape: 'rectangle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'SELECT',
      label: 'OK',
      position: { x: 206, y: 405 },
      size: { width: 60, height: 60 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 452, y: 470 },
      size: { width: 20, height: 26 },
      shape: 'rectangle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 276, y: 646 },
      size: { width: 26, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '←',
      position: { x: 130, y: 750 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 273, y: 750 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 420, y: 750 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
  },
};
