export const firetvRemoteConfig = {
  remote_info: {
    name: 'FireTV',
    type: 'ir_remote' as const,
    image_url: '/firetv_remote.png',
    default_scale: 1,
    min_scale: 0.3,
    max_scale: 1.0,
    button_scale_factor: 4,
    global_offset: { x: 0, y: 0 },
    text_style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '2px 2px 4px rgba(0,0,0,0.9)',
    },
  },
  panel_layout: {
    collapsed: {
      width: '160px',
      height: '300px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '240px',
      height: '600px',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: true,
    header: {
      height: '40px',
      fontSize: '0.875rem',
      fontWeight: 'bold',
      iconSize: 'small',
      padding: '8px',
      backgroundColor: '#1E1E1E',
      borderColor: '#333',
      textColor: '#ffffff',
    },
  },
  remote_layout: {
    collapsed: {
      width: '120px',
      height: '240px',
      scale: 0.6,
      padding: '10px',
    },
    expanded: {
      width: '400px',
      height: '300px',
      scale: 1.0,
      padding: '50px',
    },
    background_image: {
      url: '/firetv_remote.png',
      width: 400,
      height: 300,
    },
    global_offset: {
      x: 0,
      y: 0,
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 122, y: 65 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 240, y: 268 },
      size: { width: 24, height: 16 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 110, y: 400 },
      size: { width: 16, height: 24},
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 178, y: 338 },
      size: { width: 55, height: 55 },
      shape: 'circle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 396, y: 400 },
      size: { width: 16, height: 24 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 240, y: 560 },
      size: { width: 22, height: 16 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 110, y: 644 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 236, y: 644 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'HOME',
    },
    menu: {
      key: 'MENU',
      label: '',
      position: { x: 360, y: 644 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'MENU',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 112, y: 770 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'REWIND',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '',
      position: { x: 236, y: 768 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'PLAY_PAUSE',
    },
    fast_forward: {
      key: 'FORWARD',
      label: '',
      position: { x: 360, y: 768 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'FORWARD',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 234, y: 896 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 234, y: 1016 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'MUTE',
      label: '',
      position: { x: 112, y: 894 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'MUTE',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: 'CH+',
      position: { x: 366, y: 1012 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'CHANNEL_UP',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: 'CH-',
      position: { x: 112, y: 1012 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'CHANNEL_DOWN',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 136, y: 70 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 264, y: 304 },
      size: { width: 26, height: 20 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 106, y: 450 },
      size: { width: 20, height: 26 },
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 196, y: 385 },
      size: { width: 58, height: 58 },
      shape: 'circle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 442, y: 450 },
      size: { width: 20, height: 26 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 264, y: 618 },
      size: { width: 26, height: 20 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 122, y: 720 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 264, y: 720 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'HOME',
    },
    menu: {
      key: 'MENU',
      label: '',
      position: { x: 412, y: 720 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'MENU',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 122, y: 860 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'REWIND',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '',
      position: { x: 264, y: 860 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'PLAY_PAUSE',
    },
    fast_forward: {
      key: 'FORWARD',
      label: '',
      position: { x: 408, y: 860 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'FORWARD',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 264, y: 1002 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 264, y: 1140 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'MUTE',
      label: '',
      position: { x: 122, y: 1002 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'MUTE',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: 'CH+',
      position: { x: 408, y: 1140 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'CHANNEL_UP',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: 'CH-',
      position: { x: 122, y: 1140 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'CHANNEL_DOWN',
    },
  },
};
