export const firetvRemoteConfig = {
  remote_info: {
    name: 'Fire TV',
    type: 'ir_remote' as const,
    image_url: '/firetv_remote.png',
    default_scale: 1,
    min_scale: 0.3,
    max_scale: 1.0,
    button_scale_factor: 4,
    global_offset: { x: 0, y: 0 },
    text_style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '2px 2px 4px rgba(0,0,0,0.9)',
    },
  },
  panel_layout: {
    collapsed: {
      width: '160px',
      height: '300px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '240px',
      height: '600px',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: true,
    header: {
      height: '48px',
      fontSize: '0.875rem',
      fontWeight: 'bold',
      iconSize: 'small',
      padding: '8px',
      backgroundColor: '#1E1E1E',
      borderColor: '#333',
      textColor: '#ffffff',
    },
  },
  remote_layout: {
    collapsed: {
      width: '250px',
      height: '700px',
      url: '/firetv_remote.png',
    },
    expanded: {
      width: '250px',
      height: '700px',
      url: '/firetv_remote.png',
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 100, y: 20 },
      size: { width: 12, height: 12 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 100, y: 80 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 75, y: 115 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 100, y: 120 },
      size: { width: 25, height: 25 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 125, y: 115 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 100, y: 150 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '↺',
      position: { x: 75, y: 180 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 100, y: 180 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 125, y: 180 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 130, y: 26 },
      size: { width: 16, height: 16 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 130, y: 82 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 100, y: 112 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 130, y: 112 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 160, y: 112 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 130, y: 142 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '↺',
      position: { x: 100, y: 172 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 130, y: 172 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 160, y: 172 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
  },
};
