import { InfraredRemoteConfig, INFRARED_REMOTE_DEFAULTS } from './infraredRemoteBase';

export const samsungRemoteConfig: InfraredRemoteConfig = {
  remote_info: {
    ...INFRARED_REMOTE_DEFAULTS.remote_info,
    name: 'Samsung Remote',
    image_url: '/samsung_remote.png',
  },
  panel_layout: {
    ...INFRARED_REMOTE_DEFAULTS.panel_layout,
  },
  remote_layout: {
    ...INFRARED_REMOTE_DEFAULTS.remote_layout,
    background_image: {
      url: '/samsung_remote.png',
      width: 200,
      height: 500,
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 100, y: 20 },
      size: { width: 12, height: 12 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    voice: {
      key: 'VOICE',
      label: '🎤',
      position: { x: 100, y: 45 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Voice button',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 100, y: 90 },
      size: { width: 15, height: 12 },
      shape: 'rectangle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 75, y: 115 },
      size: { width: 12, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 100, y: 120 },
      size: { width: 25, height: 25 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 125, y: 115 },
      size: { width: 12, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 100, y: 150 },
      size: { width: 15, height: 12 },
      shape: 'rectangle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '←',
      position: { x: 75, y: 180 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 100, y: 180 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 125, y: 180 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
    rewind: {
      key: 'REWIND',
      label: '<<',
      position: { x: 75, y: 210 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Rewind button',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '⏯',
      position: { x: 100, y: 210 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Play/pause button',
    },
    fast_forward: {
      key: 'FAST_FORWARD',
      label: '>>',
      position: { x: 125, y: 210 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Fast forward button',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '+',
      position: { x: 100, y: 240 },
      size: { width: 15, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Volume up button',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '-',
      position: { x: 100, y: 270 },
      size: { width: 15, height: 15 },
      shape: 'rectangle' as const,
      comment: 'Volume down button',
    },
    mute: {
      key: 'MUTE',
      label: '🔇',
      position: { x: 100, y: 300 },
      size: { width: 15, height: 15 },
      shape: 'circle' as const,
      comment: 'Mute button',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 130, y: 26 },
      size: { width: 16, height: 16 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    voice: {
      key: 'VOICE',
      label: '🎤',
      position: { x: 130, y: 58 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Voice button',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 130, y: 117 },
      size: { width: 20, height: 16 },
      shape: 'rectangle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 97, y: 149 },
      size: { width: 16, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 130, y: 156 },
      size: { width: 32, height: 32 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 163, y: 149 },
      size: { width: 16, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 130, y: 195 },
      size: { width: 20, height: 16 },
      shape: 'rectangle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '←',
      position: { x: 97, y: 234 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 130, y: 234 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 163, y: 234 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
    rewind: {
      key: 'REWIND',
      label: '<<',
      position: { x: 97, y: 273 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Rewind button',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '⏯',
      position: { x: 130, y: 273 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Play/pause button',
    },
    fast_forward: {
      key: 'FAST_FORWARD',
      label: '>>',
      position: { x: 163, y: 273 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Fast forward button',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '+',
      position: { x: 130, y: 312 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Volume up button',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '-',
      position: { x: 130, y: 351 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Volume down button',
    },
    mute: {
      key: 'MUTE',
      label: '🔇',
      position: { x: 130, y: 390 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Mute button',
    },
  },
} as const;

export type SamsungRemoteConfig = typeof samsungRemoteConfig;
