export const samsungRemoteConfig = {
  remote_info: {
    name: 'Samsung',
    type: 'ir_remote' as const,
    image_url: '/samsung_remote.png',
    default_scale: 1,
    min_scale: 0.3,
    max_scale: 1.0,
    button_scale_factor: 4,
    global_offset: { x: 0, y: 0 },
    text_style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '2px 2px 4px rgba(0,0,0,0.9)',
    },
  },
  panel_layout: {
    collapsed: {
      width: '160px',
      height: '300px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '240px',
      height: '600px',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: true,
    header: {
      height: '40px',
      fontSize: '0.875rem',
      fontWeight: 'bold',
      iconSize: 'small',
      padding: '8px',
      backgroundColor: '#1E1E1E',
      borderColor: '#333',
      textColor: '#ffffff',
    },
  },
  remote_layout: {
    collapsed: {
      width: '120px',
      height: '240px',
      scale: 0.6,
      padding: '10px',
    },
    expanded: {
      width: '200px',
      height: '500px',
      scale: 1.0,
      padding: '25px',
    },
    background_image: {
      url: '/eos_remote.png',
      width: 200,
      height: 500,
    },
    global_offset: {
      x: 0,
      y: 0,
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 132, y: 66 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    nav_up: {
      key: 'UP',
      label: '',
      position: { x: 249, y: 850 },
      size: { width: 18, height: 22 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '',
      position: { x: 128, y: 960 },
      size: { width: 24, height: 18 },
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'OK',
      label: '',
      position: { x: 240, y: 954 },
      size: { width: 22, height: 22 },
      shape: 'rectangle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '',
      position: { x: 340, y: 960 },
      size: { width: 24, height: 18 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '',
      position: { x: 249, y: 1056 },
      size: { width: 18, height: 22 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 128, y: 1068 },
      size: { width: 24, height: 18 },
      shape: 'rectangle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 238, y: 742 },
      size: { width: 24, height: 24 },
      shape: 'rectangle' as const,
      comment: 'HOME',
    },
    menu: {
      key: 'MENU',
      label: '',
      position: { x: 140, y: 742 },
      size: { width: 24, height: 24 },
      shape: 'rectangle' as const,
      comment: 'MENU',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: '',
      position: { x: 350, y: 520 },
      size: { width: 22, height: 24 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_UP',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: '',
      position: { x: 350, y: 640 },
      size: { width: 22, height: 24 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_DOWN',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 136, y: 520 },
      size: { width: 22, height: 24 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 138, y: 640 },
      size: { width: 22, height: 24 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'MUTE',
      label: '',
      position: { x: 244, y: 524 },
      size: { width: 22, height: 22 },
      shape: 'rectangle' as const,
      comment: 'MUTE',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 126, y: 1293 },
      size: { width: 16, height: 14 },
      shape: 'rectangle' as const,
      comment: 'REWIND',
    },
    play: {
      key: 'PLAY',
      label: '',
      position: { x: 208, y: 1293 },
      size: { width: 16, height: 14 },
      shape: 'rectangle' as const,
      comment: 'PLAY',
    },
    pause: {
      key: 'PAUSE',
      label: '',
      position: { x: 290, y: 1293 },
      size: { width: 16, height: 14 },
      shape: 'rectangle' as const,
      comment: 'PAUSE',
    },
    rec: {
      key: 'RECORD',
      label: '',
      position: { x: 123, y: 1150 },
      size: { width: 18, height: 16 },
      shape: 'rectangle' as const,
      comment: 'RECORD',
    },
    fast_forward: {
      key: 'FORWARD',
      label: '',
      position: { x: 374, y: 1293 },
      size: { width: 16, height: 14 },
      shape: 'rectangle' as const,
      comment: 'FORWARD',
    },
    tv_guide: {
      key: 'TVGUIDE',
      label: '',
      position: { x: 348, y: 420 },
      size: { width: 24, height: 18 },
      shape: 'rectangle' as const,
      comment: 'TVGUIDE',
    },
    number_1: {
      key: 'KEY_1',
      label: '',
      position: { x: 124, y: 168 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_1',
    },
    number_2: {
      key: 'KEY_2',
      label: '',
      position: { x: 236, y: 168 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_2',
    },
    number_3: {
      key: 'KEY_3',
      label: '',
      position: { x: 348, y: 168 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_3',
    },
    number_4: {
      key: 'KEY_4',
      label: '',
      position: { x: 124, y: 248 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_4',
    },
    number_5: {
      key: 'KEY_5',
      label: '',
      position: { x: 236, y: 248 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_5',
    },
    number_6: {
      key: 'KEY_6',
      label: '',
      position: { x: 348, y: 248 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_6',
    },
    number_7: {
      key: 'KEY_7',
      label: '',
      position: { x: 124, y: 336 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_7',
    },
    number_8: {
      key: 'KEY_8',
      label: '',
      position: { x: 236, y: 336 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_8',
    },
    number_9: {
      key: 'KEY_9',
      label: '',
      position: { x: 348, y: 336 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_9',
    },
    number_0: {
      key: 'KEY_0',
      label: '',
      position: { x: 236, y: 420 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_0',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 145, y: 71 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    nav_up: {
      key: 'UP',
      label: '',
      position: { x: 284, y: 952 },
      size: { width: 18, height: 26 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '',
      position: { x: 144, y: 1076 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'OK',
      label: '',
      position: { x: 276, y: 1064 },
      size: { width: 22, height: 24 },
      shape: 'rectangle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '',
      position: { x: 390, y: 1076 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '',
      position: { x: 284, y: 1170 },
      size: { width: 18, height: 26 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 138, y: 1188 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 272, y: 824 },
      size: { width: 24, height: 26 },
      shape: 'rectangle' as const,
      comment: 'HOME',
    },
    menu: {
      key: 'MENU',
      label: '',
      position: { x: 140, y: 842 },
      size: { width: 28, height: 24 },
      shape: 'rectangle' as const,
      comment: 'MENU',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: '',
      position: { x: 386, y: 580 },
      size: { width: 28, height: 26 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_UP',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: '',
      position: { x: 386, y: 720 },
      size: { width: 28, height: 26 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_DOWN',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 144, y: 580 },
      size: { width: 28, height: 26 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 144, y: 720 },
      size: { width: 28, height: 26 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'MUTE',
      label: '',
      position: { x: 276, y: 580 },
      size: { width: 24, height: 26 },
      shape: 'rectangle' as const,
      comment: 'MUTE',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 140, y: 1446 },
      size: { width: 16, height: 14 },
      shape: 'rectangle' as const,
      comment: 'REWIND',
    },
    play: {
      key: 'PLAY',
      label: '',
      position: { x: 234, y: 1446 },
      size: { width: 16, height: 14 },
      shape: 'rectangle' as const,
      comment: 'PLAY',
    },
    pause: {
      key: 'PAUSE',
      label: '',
      position: { x: 330, y: 1446 },
      size: { width: 16, height: 14 },
      shape: 'rectangle' as const,
      comment: 'PAUSE',
    },
    rec: {
      key: 'RECORD',
      label: '',
      position: { x: 140, y: 1288 },
      size: { width: 18, height: 16 },
      shape: 'rectangle' as const,
      comment: 'RECORD',
    },
    fast_forward: {
      key: 'FORWARD',
      label: '',
      position: { x: 424, y: 1446 },
      size: { width: 16, height: 14 },
      shape: 'rectangle' as const,
      comment: 'FORWARD',
    },
    tv_guide: {
      key: 'TVGUIDE',
      label: '',
      position: { x: 398, y: 468 },
      size: { width: 24, height: 18 },
      shape: 'rectangle' as const,
      comment: 'TVGUIDE',
    },
    number_1: {
      key: 'KEY_1',
      label: '',
      position: { x: 146, y: 192 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_1',
    },
    number_2: {
      key: 'KEY_2',
      label: '',
      position: { x: 270, y: 192 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_2',
    },
    number_3: {
      key: 'KEY_3',
      label: '',
      position: { x: 394, y: 192 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_3',
    },
    number_4: {
      key: 'KEY_4',
      label: '',
      position: { x: 146, y: 285 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_4',
    },
    number_5: {
      key: 'KEY_5',
      label: '',
      position: { x: 270, y: 285 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_5',
    },
    number_6: {
      key: 'KEY_6',
      label: '',
      position: { x: 394, y: 285 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_6',
    },
    number_7: {
      key: 'KEY_7',
      label: '',
      position: { x: 146, y: 377 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_7',
    },
    number_8: {
      key: 'KEY_8',
      label: '',
      position: { x: 270, y: 377 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_8',
    },
    number_9: {
      key: 'KEY_9',
      label: '',
      position: { x: 394, y: 377 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_9',
    },
    number_0: {
      key: 'KEY_0',
      label: '',
      position: { x: 270, y: 468 },
      size: { width: 26, height: 18 },
      shape: 'rectangle' as const,
      comment: 'KEY_0',
    },
  },
};
